### ISSUE TITLE
Option to set the delimiter characters for tokenizing

### ISSUE THREAD

**Issue by lnwdr** [olivernn/lunr.js#102]
Currently, the default tokenizer only splits token on whitespace with `/\s+/`. To use other delimiting characters (e.g. "-") I currently have to set a completely new tokenizer function that mostly a copy of the original one.

There should be an option to set the delimiter characters or maybe to pass in a callback that does the splitting.

**Comment by olivernn** [comment]
In the [latest (0.6.0)](https://github.com/olivernn/lunr.js/releases/tag/v0.6.0) version I've added a property `lunr.tokenizer.seperator` that can be overridden to change the regex that is used to split a string into tokens.
