### ISSUE TITLE
reduce a score precision to decrease the index file size?

### ISSUE THREAD

**Issue by Qvatra** [olivernn/lunr.js#105]
is there a way to reduce the precision of the score number to reduce the index size?

**Comment by Fil** [comment]
1/824 would be an exact and compact way of writing 0.00121345443566670… :)

**Comment by olivernn** [comment]
@fil Serialising the tf values as rationals is a neat idea!

I [spiked](https://github.com/olivernn/lunr.js/commit/4109938b3180f1ce97dcb902651715031d6ce084) something to try and see what improvement was to be had. The size of the index was reduced by roughly ~20% before gzip.

As discussed in the commit message there was an unacceptable decrease in performance for both loading the index and searching the index. The impact was such that, as it currently stands, I think its a non-starter.

My implementation is probably not the greatest though, so if someone wants to take a look and see if they can wring any more performance out of it I'd be more than happy to take another look, I think the following are the major areas for improvement:

* The algorithm for converting a decimal to a fraction is completely unoptimised
* Walking the entire tree manually on load could be done more efficiently perhaps

The biggest problem is that on load every tf value must be parsed into a Fraction. The alternative is to do this lazily, I didn't explore this direction much, there might be some gains to be made here.

@Qvatra on the same branch I also made a change to [trim the serialised index](https://github.com/olivernn/lunr.js/commit/f0bf8221bf599287d042aaf9a978eafe51f5c639). This change seems more promising and will probably make it into a version 0.6.0 of lunr. The only concern I have is that it limits any other meta data being added about a token, e.g. position, but perhaps until that day comes it might be a worthwhile change. It is worth noting that I haven't tested the savings after gzip compression.

**Comment by olivernn** [comment]
I've just released version 2.0.2 which [incorporates this idea](https://github.com/olivernn/lunr.js/commit/5114f6c764a8346cce96dc1a7498ab2a0d31d2d0), it reduced the size of serialised indexes by about ~15% before and after compression.
