### ISSUE TITLE
Behavior of Special Characters.

### ISSUE THREAD

**Issue by justinpathrose** [olivernn/lunr.js#112]
Hi ,

Not sure if this is the right place to discuss this. But desperately need a solution to a problem I am facing. I am using lunr.js in one of my projects. I am not able to properly handle special characters in my search. For eg, when searching in my documents with strings containing special characters like "who's" the search function gives an output even though document does not contain the word "who's". Are special characters added to the stop words. How can I avoid this. Thanks in advance.

**Comment by olivernn** [comment]
Sorry for the _very_ late response to this issue.

Lunr should handle characters like apostrophes well, the pipeline will transform the token into what ends up in the index, a quick check shows that by default `who's` will be transformed to `who'`. This seems slightly strange and could possibly be handled better.

Could you put together a reduced test case that shows this behaviour that you think is incorrect and I can look into it further.

**Comment by olivernn** [comment]
Closing this as I need more information to be able to offer a bug fix. Please re-open if you can provide more information to help me reproduce.
