### ISSUE TITLE
Is it possible to query by field?

### ISSUE THREAD

**Issue by stephengoodwin** [olivernn/lunr.js#125]
Current query:

``` javascript
index.search('austin')
```

Desired query:

``` javascript
index.search('city:austin')
```

**Comment by justinlinz** [comment]
Not sure if this is the solution shaun4477 was referring to, but you can prefix your value with propertyname: when indexing, and get decent results.  There are probably some drawbacks with this approach as well, but depending on what you need might get the job done.
``` js
var data = [{
            refId:'68977',
            name:'Dilbert',
            title:'Engineer'
        },{
            refId:'45674',
            name:'Wally',
            title:'Engineer',
        },{
            refId:'00014',
            name:'Pointy-Haired Boss',
            title:'Manager'
        }
        ];

        var employees = lunr(function () {
            this.ref('refId');
            this.field('name');
            this.field('title');
        });

        data.forEach(function(r){
            employees.add({
                    refId:'refId:'+ r.refId,
                    name:'name:'+ r.name,
                    title:'title:'+ r.title
                }
            );
        });

        var results = employees.search("name:Dilbert title:Engineer");
```

**Comment by tirana** [comment]
+1

**Comment by olivernn** [comment]
I have published an [alpha release](https://github.com/olivernn/lunr.js/commit/40140f023923d22575d73cdb1d06b7908ec943a0) of the next version of lunr with support for query by field.

In addition I've put together a [basic](https://github.com/olivernn/moonwalkers) [demo](https://olivernn.github.io/moonwalkers/) that should allow you to play around with the search by field feature.

**Comment by olivernn** [comment]
Closing this now as v2 is now available in npm.
