### ISSUE TITLE
Is it possible to determine the field that matched a query?

### ISSUE THREAD

**Issue by jbohren** [olivernn/lunr.js#126]
For example, if a search entry has `summary` and `content` fields, could is it possible to determine which of the fields matched a given query without searching the individual fields again?

**Comment by dominicbarnes** [comment]
I'd like to know the answer to this too.

**Comment by olivernn** [comment]
Right now, its not possible.

I'm not against adding such a feature, I think currently it is not trivial to add this functionality, also I have a couple of changes I'd like to make to how results are returned/generated by lunr.

I'll definitely keep this feature in mind when re-working the results from a search.

**Comment by jbohren** [comment]
Thanks for the feedback, @olivernn.
