### ISSUE TITLE
Is there a way to clear the index? (Removing all docs)

### ISSUE THREAD

**Issue by sanfilippopablo** [olivernn/lunr.js#127]
I need this for testing purposes.

**Comment by olivernn** [comment]
There is no `clear` method available on index to do this. If you want a fresh index you should just create a new, empty index. Outside of testing purposes I don't really see the need for such a function.

**Comment by patrickml** [comment]
@olivernn im in need of this functionality because we load all documents into memory so they can be search quickly, but we need a way to update the docs in memory by clearing the indexed data and reloading it.

**Comment by olivernn** [comment]
@patrickml do you need to update _all_ the documents at once, or individually?

You can update a single document in the index using the [`lunr.Index.prototype.update`](http://lunrjs.com/docs/#update) method, this actually just removes and then re-adds the document.

If you are doing this in bulk then it _really_ is simpler to just create a whole new index, is there something I missing that means this approach won't work for your use case?
