### ISSUE TITLE
Meteor package

### ISSUE THREAD

**Issue by lb-** [olivernn/lunr.js#128]
I would like to suggest that this package be available as a meteor package also. 

See here for a fork of lunr as a current working package. 

https://github.com/lb-/lunr.js/

Changes include the added meteor directory (meteor specific integration and tests). Also the package.js which is the meteor package definition file. 

Happy to keep this as a fork but would love to see it move in to the main repository, this would mean pushing updates to Atmosphere as they are built.

Lunr is incredible and suits the flow of meteor on the client (& even server) as mongo db is the built in db. 

Thanks.

**Comment by olivernn** [comment]
Sorry for _very_ late reply.

I think I'd prefer to not include the Meteor build artefacts in this repository, and that the meteor build process should live in another repo that either forks or includes this one as a submodule.
