### ISSUE TITLE
New feature in Index class

### ISSUE THREAD

**Issue by jnovos** [olivernn/lunr.js#130]
Hi, 
I would like to add a new method into Index class.
lunr.Index.prototype.indexJson = function (index) {
        return JSON.stringify(index)
}
I need this method to finish a extension for Middleman.

It's possible
thank you

**Comment by olivernn** [comment]
What is the `index` argument that your function takes?

Do you need a method on the index to do that?

The index object already has the ability to be converted to JSON by just calling `JSON.stringify(idx)`, where idx is the index object. I'd rather not have the index have a method that just wraps `JSON.stringify` as I'm not sure it adds much value.

If you really do need this to be a method on the index object then consider writing a plugin, some details here - http://lunrjs.com/docs/#use

For this case it might look a little bit like this:

    var indexJSONPlugin = function () {
      this.indexJson = function (index) {
        return JSON.stringify(index)
      }
    }

Then use your plugin like this:

    idx.use(indexJSONPlugin)

Feel free to re-open if I've misunderstood your use case, or if you have any other questions.

**Comment by jnovos** [comment]
Hi Oliver,
Good nigth, :-), 
I am executing lunr.js into a  V8 JavaScript interpreter in Ruby. I need execute JSON.stringify into of context the lunr.js. 
Example ruby:
cxt = V8::Context.new
cxt.load(folder_lunar_js
val = cxt.eval('lunr')
idx = val.call(lunr_conf)
idx.add(doc)
idx.indexJson() //Result = json of index

Why?, It is more easy for instalation of middleman extension, only it install bower  ;-)

thanks for you tim

**Comment by jnovos** [comment]
sorry the function 


    /**
     * Convert Index class into json representation.
     *
     * @returns {String} representation of {lunr.Index} in json
     * @memberOf Index
     */
    lunr.Index.prototype.indexJson = function () {
        return JSON.stringify(this)
    }
