### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lu4** [olivernn/lunr.js#136]
Hi Oliver,

Is it possible to request a feature in exchange for money? I'd like to use your lib in my open-source project but unfortunately lunrjs interface doesn't allow me to do that. The reason for me to ask for such thing is that project I'm working on will never get born if I will start reverse engineering into another library. I have fairly limited personal budget for such request because my project is non-profit open source, but still if the idea itself is close to you, let's discuss the details in private. 

Thank you in advance,

Best regards,
Denis

**Comment by olivernn** [comment]
DM me your email on twitter (I'm @olivernn) and we can discuss further. I'm not against to people sponsoring a feature, so long as it makes sense for the project as a whole.
