### ISSUE TITLE
.travis.yml nodejs version too old

### ISSUE THREAD

**Issue by weixsong** [olivernn/lunr.js#150]
it seems node.js 0.8 is very old version of node.js, maybe currently few people use node.js 0.8.

And for issue https://github.com/olivernn/lunr.js/issues/140 , the make server fix is also targeted at node.js 0.10 and 0.12.

**Comment by olivernn** [comment]
I've pushed a change to add 0.12, I've kept 0.8 around to keep backwards compatibility, thanks for pointing this out to me.
