### ISSUE TITLE
Example: Unable to search for any keyword in the body of the question

### ISSUE THREAD

**Issue by srph** [olivernn/lunr.js#155]
The example states that all three fields (title, tags, body) were indexed. However, I couldn't get the results I expect when using any keyword from the body of the question. The rest works fine.

Example:

---

# Why does my checkbox return the wrong state?

`javascript jquery html`

I'm really confused. I have the following:

```html
<input class="check-box" 
  id="Data__Correct" 
  name="Data.Correct" 
  type="checkbox" value="Data.Correct" />
```

When I put a check in the checkbox and check with fiddler I see it's sending back:

`Data.Correct    False`
I thought it should be the other way around. What's happening?

---

When I search with `I'm really confused`, or any possible pattern taken from the body of any question , I don't get any results.

**Comment by olivernn** [comment]
This is an issue with the example data, it contains html tags still. If you try searching for "really confusing" you should find the correct document, also searching for "I'm" will find other documents that contain "I'm". 

The question you have shared actually has the token "<p>I'm" which isn' matched by "I'm". This is more of a problem with the example and its data than with lunr, i.e. the html should be stripped before being indexed if possible.

**Comment by srph** [comment]
I see! Thanks a lot for this awesome work :+1:
