### ISSUE TITLE
Get surrounding text for search. 

### ISSUE THREAD

**Issue by Tombert** [olivernn/lunr.js#158]
Hello!  I am curious about this...when you search on Google for something, you get the results (obviously), and then a little excerpt of the page with the surrounding text.  Is there any mechanism in which to do this in Lunr.js?

**Comment by olivernn** [comment]
Currently, no :disappointed:

This is a [very](https://github.com/olivernn/lunr.js/pull/58) [popular](https://github.com/olivernn/lunr.js/issues/25) [request](https://github.com/olivernn/lunr.js/issues/97), the trouble is that it is completely incompatible with the current way lunr stores its index of documents and performs searches. As such implementing it is not easy, not to say it is something that will _never_ happen, just that it probably won't be available anytime soon.
