### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by gmarty** [olivernn/lunr.js#16]
I know the web is English centric, but that would be nice to support more languages through a plugin system.
Fortunately there are several tools out there for tokenization and stemming that can be used:
- [Natural](https://github.com/NaturalNode/natural) has tokenizers, stemmers, stop words and even inflectors for several languages
- [jssnowball](https://github.com/mazko/jssnowball) also has a nice collection of stemmers
- Detecting the language may also come handy: [language-identifier](https://github.com/tomayac/language-identifier) and [cld-js](https://github.com/jaukia/cld-js) can help

I don't really have the time to work on this feature, but I'd like to see lunr.js going this way.

**Comment by jlambe** [comment]
Hi @olivernn. Found your project and I was wondering if the latest release supports other languages or we still need to fetch the i18n branch?
Also, I can't find a way to use the stopWord filter function from the docs, do you have an example on how to add stop words before indexing content?
Thanks
