### ISSUE TITLE
Reverse token before suffix stemmer

### ISSUE THREAD

**Issue by Adria2** [olivernn/lunr.js#165]
I think tokens should be reversed before stemming, to massively reduce back-tracking for the 12 or so tests each token has to pass.

For example:
<code>
^(.+?)(ational|tional|enci|anci|izer|bli|alli|entli|eli|ousli|ization|ation|ator|alism|iveness|fulness|ousness|aliti|iviti|biliti|logi)
</code>
(random)izer matched in 142 steps
(random)ize failed in 239 steps
<code>
^(lanoita|lanoit|icne|icna|rezi|ilb|illa|iltne|ile|ilsuo|noitazi|noita|rota|msila|ssenevi|ssenluf|ssensuo|itila|itivi|itilib|igol)(.+)
</code>
rezi(modnar) matched in 12 steps
ezi(modnar) failed in 23 steps

**Comment by olivernn** [comment]
Sounds interesting, though I'm not sure I fully understand!

So the stemmer pipeline function would reverse the token, do the stemming and then unreverse the stemmed token before passing it on?

I'm open to this, but I'd like to see some benchmarks, would you mind putting together a pull request with the required changes so we can see some data on what impact this has on the performance?

**Comment by Adria2** [comment]
Yes that was the gist of it. However I just did a quick benchmark/sanity check, and it's not worth it. The stemmer just doesn't account for enough of the total time.
There were some trivial changes which shaved off around 5% in my 61 chapter novel test though.

Here, replace is an expensive way of slicing off just the last character, and less readable perhaps.
<pre>var re_1b_2 = /.$/;
w.replace(re_1b_2,"") === w.slice(0, -1)
</pre>
Most of the saving came from here I think, as it's such a common case in English. The token already passed the regex test, so there’s no point in matching it again just to slice off "es".
<pre>
-if (re.test(w)) { w = w.replace(re,"$1$2"); }
-else if (re2.test(w)) { w = w.replace(re2,"$1$2"); }
+if (re.test(w)) { w = w.slice(0, -2); }
+else if (re2.test(w)) { w = w.slice(0, -1); }
</pre>

**Comment by olivernn** [comment]
Closing this, feel free to open a PR with your changes if you think the perf gain is worth it.
