### ISSUE TITLE
Adding lunr.js v0.5.11 breaks Angular application

### ISSUE THREAD

**Issue by tobilg** [olivernn/lunr.js#168]
I'm trying to add the lunr.js v0.5.11 to my angular project. I see the behavior that when I add the lunr.js file before any Angular (module) file, Angular is crashing with a nomod error.

If I remove lunr.js again, everything works as expected.

**Comment by olivernn** [comment]
Do you have a reduced test case to help me (or the angular devs) reproduce the issue?

I'm not familiar with angular so I don't know what a nomod error is. If you provide me with some more detail I might be able to help though.

**Comment by tobilg** [comment]
Sorry, this was because I referenced the library like 

    <script src="javascripts/vendor/lunr/lunr.js"/>

instead of 

    <script src="javascripts/vendor/lunr/lunr.js"></script>

in the latest Chrome. If I use the latter, it works flawlessly.
