### ISSUE TITLE
Unable to load data from json file

### ISSUE THREAD

**Issue by smrita-garg** [olivernn/lunr.js#171]
Hi All,

I am at learning phase of EXT JS in which I facing issue,
  I am unable to populate the data from json file into a combobox .
Below is the code I am using 

margin:'7 6 5 5',
            xtype:'combobox',
            fieldLabel:'Language',
            id:'combo',
            width:190,
            emptyText: '--Select language--',
            labelWidth: 60,
            store:  new Ext.data.Store({
                type: 'ajax',
                autoLoad: true,
                url: 'C:\Users\Administrator\Desktop\dropdown.json',
                storeId: 'projectDropDown',
                reader: new Ext.data.JsonReader(
                {
                    type: 'json',
                    root: 'projects',
                    idProperty: 'ProjectID',
                }),
                
                fields: [ 'ProjectID', 'ProjectName' ]
 }),
            queryMode: 'local',
            valueField:'ProjectID',
            displayField:'ProjectName',
           }

My json file looks like this

{
    "projects" : [
       {"ProjectID":"1","ProjectName":"Mike's Test Project"},
       {"ProjectID":"2","ProjectName":"My Second Test Project"}
       
    ]
}

Please help as it is very urgent!!

Thanks in advance

**Comment by olivernn** [comment]
Its not clear from your description that this is an issue with lunr.js.

I'm not at all familiar with EXT.js so can't offer any advice on how to use it.

Feel free to open an issue if you discover a bug or a problem with lunr, for general questions on how to integrate etc you might find [stackoverflow](http://stackoverflow.com/questions/tagged/lunrjs) better.
