### ISSUE TITLE
Tokenizer crash if element of array is null

### ISSUE THREAD

**Issue by desh901** [olivernn/lunr.js#172]
If an element of the array is null console returns "TypeError: t is null.

lunr.tokenizer = function (obj) {
  if (!arguments.length || obj == null || obj == undefined) return []
  if (Array.isArray(obj)) return obj.map(function (t) { return t.toLowerCase() })

  return obj.toString().trim().toLowerCase().split(/[\s\-]+/)
}

Btw, thanks for your awesome work!

**Comment by awcab** [comment]
I submitted a pull request (#174) today that I think will fix this one.

**Comment by olivernn** [comment]
I've pushed a fix for this in version [0.6.0](https://github.com/olivernn/lunr.js/releases/tag/v0.6.0), please take a look and let me know if you have any issues.
