### ISSUE TITLE
does it support Chinese?

### ISSUE THREAD

**Issue by luxuryzhou** [olivernn/lunr.js#173]
as subject
searching Chinese characters

**Comment by olivernn** [comment]
Out of the box lunr only supports English. However there is the [lunr-languages project](https://github.com/MihaiValentin/lunr-languages) which supports other languages, at current it doesn't seem to support Chinese though.

A previous [issue](https://github.com/olivernn/lunr.js/issues/91) discussed this and I still think it would be awesome for someone to add Chinese support to lunr-languages, but I only speak English and so can't be much help.

Alternatively I see @codepiano has a [fork of lunr](https://github.com/codepiano/lunr.js) that claims to support Chinese, perhaps you could extract the specifics into a Chinese plugin for lunr, let me know if you need any advice on what would be required.

**Comment by codepiano** [comment]
My fork of lunr relys a nodejs module to tokenize Chinese words,so if you want to use it in browser,you should dump the idx into a json format file.

**Comment by Trolleymusic** [comment]
@codepiano would you be willing to contribute a Chinese language version to the [lunr-languages project](https://github.com/MihaiValentin/lunr-languages)? - they already have a Japanese version which you might be able to use as a template of sorts.

**Comment by codepiano** [comment]
@Trolleymusic I'll try, but I'm not good at this, so It may take a long time.
