### ISSUE TITLE
Document serializing/loading indices

### ISSUE THREAD

**Issue by rstacruz** [olivernn/lunr.js#183]
Is this the correct way to save/load indices? The documentation doesn't say much about this.

```js
var idx = lunr(...)
var data = JSON.stringify(idx)
```

```js
var idx = lunr.Index.load(JSON.parse(data))
```

**Comment by olivernn** [comment]
Yep, thats the right way of loading/serialising. The documentation could be a little clearer on this, I really need to spend some time on writing guides for common things like this.
