### ISSUE TITLE
ES3 support broken even with ES5-Shim or Augment.js

### ISSUE THREAD

**Issue by jkellerer** [olivernn/lunr.js#185]
On the attempt to use *Windows Script Host 5.x* ("```cscript.exe```") for creating an offline index of a bunch of HTML files, I found that after adding *ES5-Shim* or *Augment.js* an index can be created with this ES3 script engine but it differs completely from the version that is created with the same script using NodeJS and it is also broken.

Digging deeper I found that the reverse index part (trie) of an index that is created in an ES3 environment has no valid content. The reason is that [token_store.js](https://github.com/olivernn/lunr.js/blob/0b9d277057aaeb29dc15a979e364a519f62b21dd/lib/token_store.js) uses array-like character access on Strings, however this is a ES5 feature which cannot be ported back into an ES3 environment. ( See also [String#Character_access](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Character_access) )

The solution I applied locally is to replace all array-like access "```string[i]```" with "```string.charAt(i)```" calls. 

I'm preparing a pull-request with this change now.

**Comment by olivernn** [comment]
Thanks for the PR, I've merged in your changes in version [0.6.0](https://github.com/olivernn/lunr.js/releases/tag/v0.6.0)
