### ISSUE TITLE
Is it possible to search using advanced query string?

### ISSUE THREAD

**Issue by fmmsilva** [olivernn/lunr.js#187]
I'd like to do some advanced search. Is it possible?

Example: 'car -airplane', 'car and bike -motorbike'

**Comment by olivernn** [comment]
This is not currently possible, the query interface is very basic, all the words in the string _must_ be present in a document for the document to match.

I have plans to enable more powerful search queries, but it is something that requires a decent amount of  thought and re-work in the internals of lunr that are not going to land anytime soon I'm afraid.
