### ISSUE TITLE
Using lunr plugin works but triggers warning message

### ISSUE THREAD

**Issue by jlambe** [olivernn/lunr.js#190]
Hi,
first lunr is awesome :+1: 

Now the issue is that I'm using the `lunr.fr` plugin. It does work correctly but it keeps calling the warn utility method with this message:

- Function is not registered with pipeline. This may cause problems when serialising the index.

Is there a way to avoid this?

Here is my index code:

```js
this.index = lunr(function()
{
    this.use(lunr.fr);
    this.ref('number');
    this.field('number', {boost: 5});
    this.field('title');
    this.field('content', {boost:10});
});
```

Thanks.

**Comment by olivernn** [comment]
Which `lunr.fr` plugin are you using?

Any function in the pipeline must be [registered](http://lunrjs.com/docs/#registerFunction) so that serialising and loading a serialised index can work properly.

I'm not sure which `lunr.fr` plugin you are using, but [lunr-languages](https://github.com/MihaiValentin/lunr-languages) has many language plugins, including French, that correctly register pipeline functions. Let me know if that doesn't solve the issue.

**Comment by jlambe** [comment]
Hi, will try this one tomorrow and let you know.

**Comment by jlambe** [comment]
Finally I couldn't wait to try this. In fact I was using another lunr.fr plugin from an old issue. I've updated the code with the repository you gave me and it works like a charm.
Great library!

**Comment by drzraf** [comment]
I'm having the `Overwriting existing registered function: stopWordFilter` message, triggered by `stop_word_filter.js`
(open their /weixsong/elasticlunr.js#57 in case it'd be specific to elasticlunr.js)
The point is that `stop_word_filter.js` contains lunr.generateStopWordFilter which is generic and useful (for lunr-languages), but also registerFunction too (which is not always necessary).

**Comment by olivernn** [comment]
@drzraf What version of lunr are you using? Or are you using elasticlunr?

Registering a pipeline function is necessary for serialising indexes. With Lunr the only way you could get the warning about overwriting an existing registered function is if you are requiring that file twice, or if you have already registered a different pipeline function with the same name. Both of these cases seem to be under your control.
