### ISSUE TITLE
How does lunr handle quantifiers?

### ISSUE THREAD

**Issue by julmot** [olivernn/lunr.js#199]
I would like to know if it's possible to search for strings with quantifiers, e.g. `he*o` or `Ho? are you`. Unfortunately I can not find any information about it in the documentation.

**Comment by olivernn** [comment]
So, currently each search term gets an implicit wildcard appended to the end, so for example a search for `hello` is really a search for `hello*`.

It is not possible to place wildcards, or any other quantifiers, anywhere else in the token, nor is it possible to have an exact search term, i.e. no automatic wildcard.

**Comment by julmot** [comment]
Is it unfounded to see this as a feature request?

**Comment by missinglink** [comment]
@julmot These sort of queries are generally slow and are not well suited for an inverted index.

It's worth considering using a regex instead of a custom globby-type-query-language as per the mongodb API.

What exactly is your use case?

**Comment by julmot** [comment]
@missinglink How to use lunr with a custom regex?

I don't have a use case at the moment, I just want to give users only the best.

**Comment by olivernn** [comment]
It is something that I would like to support, to some extent anyway. @missinglink is right though, performance, especially with leading wildcards, can take a real hit when making these kind of queries.

It is not possible to query a lunr index with a regex.

**Comment by julmot** [comment]
So an option to disable quantifier search would be the solution. You could then disable it if performance is more important to you than the feature.
