### ISSUE TITLE
Get callback with found words?

### ISSUE THREAD

**Issue by julmot** [olivernn/lunr.js#200]
When using
```javascript
idx.search("search")
```
I would like to get an return value with an array containing all the words that were found in the entry, like:
```javascript
[{
    "ref": 1,
    "score": 0.87533,
    "words": ["searching", "search", "searched"]
}]
```
This would give me the opportunity to e.g. highlight exactly those words which were found. 
Is there a way?

My problem:
When using lunr in combination with something that handles search results, like a highlighting component, inconsistent behavior will happen. For example if you search for "searched" all entries with "search" or "searched" will be found. However, just "searched" will become highlighted (because those components may not contain things that lunr has built in, like stemming). So I need a way to determine exactly those words which were found in the entry by lunr. Rebuilding the algorithm seems quite excessive and unnecessary to me.

**Comment by olivernn** [comment]
lunr does not keep the unstemmed words for a document around, so any highlighting tool would need to be able to highlight based on the stem of the word, in your example "searched" will actually never appear in the index, it will be stemmed to just "search" (or whatever the stemmer reduced it to).

For this reason I _think_ the only way to solve this is to be able to return the positions of the tokens in the document, this should also lead to far greater highlighting performance, rather than having to search through the entire text of a document to find the terms to highlight.

**Comment by julmot** [comment]
I think rebuilding the algorithm of lunr would cause unwanted issues:
- double logic
- double stemming time
- double maintenance and maybe inconsistent behaviour
- from the adapter point of view non-reusable code as other libraries may have different algorithms
Therefore I would like to exclude this option.

Isn't there an option to hook into lunr to save the unstemmed words?
What exactly do you mean with position? The character index inside an element?

**Comment by julmot** [comment]
:balloon: I just saw that we've got a anniversary, the 200th issue :bowtie:

**Comment by olivernn** [comment]
Hehe, yes 2x :100: 

I think, as it stands, the current implementation of lunr has taken us as far as it's possible to go. As you say, this, and other features, are kind of incompatible with the current data structures in use, and I'm hesitant to try and shoe horn in features like this.

A better approach is rethinking some of the internals to provide better support, which is what I'm currently working on, as I'm sure you understand though this is not exactly quick and time is always limited.

Providing a means for storing the positions of terms in the index allows for highlighting matched terms as well as querying by locality. The changes to implement this also open up third-party code the ability to store other meta data about tokens that might open up some other interesting possibilities.

At a high level, I'd like to have positions stored something like this:

```javascript
    'document-id': {
      'tf': 0.1234,
      'positions': [{
         'start': 3,
         'length': 6
       }]
```

I know this doesn't really solve you're problem right now, but I think, long term, its the right decision.

**Comment by julmot** [comment]
Oliver, I didn't get you in that position thing. What exactly is this position about? Is it the position in the whole text of the document (stripped HTML)?

**Comment by olivernn** [comment]
Yes, so you would know the character in text that a token started at, as well as how long it is. This should be enough to wrap those characters in some markup that can show the highlighting.

For example, in the following document:

```
index : 012345678
doc   : hurp durp
```

**hurp** would have a start index of 0 and a length of 4
**durp** would have a start index of 5 and a length of 4

**Comment by julmot** [comment]
Well I don't know a way to handle this in a highlighting component. Such components search in HTML elements and also inside each text node in an those elements. So there an adapter would be necessary to find out which text node stores the word with a specific index and I don't know hot to start with that.

**Comment by julmot** [comment]
@olivernn To make things clear: Highlighting works based on an index if it is an index relative to the parent element. But, as you meantioned, you are thinking to implement the index of the whole document. I don't know how to map a document index with an index relative to the parent DOM element.

Can you help?

**Comment by julmot** [comment]
@olivernn I am willing to to implement an adapter, but I need your help in order to do this!

**Comment by kanatzidis** [comment]
+1 to returning match positions. It would be easy to roll our own highlighting with that. How far is the current implementation from doing that?

**Comment by julmot** [comment]
@kanatzidis As @olivernn seems to be quite inactive, maybe you can help. My problem with an index of matches _globally_ is that a conversion to an index based on HTML elements would be necessary. 

Take this HTML as an example:

```html
<p>Lorem ipsum dolor sit amet <span>Test</span> Lorem ipsum dolor sit amet</p>
```

Now, assume that lunr would return the index position of "Test": start `27`, end `31`. Now a highlighting component would need to map this index with an index relative to `<span>`, which would be `0` and `4`. I don't see a way to realize this.

**Comment by kanatzidis** [comment]
I'm not sure how you would do it operating on dom elements. In my use case I have plain text which I can modify with spans that add a highlight style.

**Comment by julmot** [comment]
@kanatzidis You're absolutely right, I've had a wrong way of thinking. Sometimes it helps to talk with others. So if lunr would return the index of matched terms an adapter could seek it out. Then a highlighting component could be called with that term.

So the only left question is, @olivernn do you need any help to realize this soon?

**Comment by olivernn** [comment]
Sorry for the lack of response, I've been spending some much needed time away from a computer!

The wrapping idea came from a library a friend create a while ago: https://github.com/benpickles/wapper, it is slightly old now, but should give some ideas for implementing the wrapping of characters in some dom element.

I'm actively working on the changes required to provide the positional information of tokens, the change is part of a larger re-work of the internals of the library. I can't commit to a date etc, but it is in progress and I hope to share what I have as soon as possible.

**Comment by julmot** [comment]
@olivernn Any update on this?

**Comment by olivernn** [comment]
I've been [working on some changes](https://github.com/olivernn/lunr.js/tree/2.x) that should enable what you need. I'm pretty close to getting at least a preview build out with some documentation, I'll be sure to update this issue when that happens.

At a high level what will happen is that the tokenizer will [keep track](https://github.com/olivernn/lunr.js/blob/2.x/lib/tokenizer.js#L30-L37) of the positions of a token within a document, this can then be returned along with some other details about the matched term with the search results. My hope is that this should provide all the information possible to enable users to highlight matched words.

**Comment by MykolaGolubyev** [comment]
Good read here. Any updates on it? Thanks!

**Comment by olivernn** [comment]
Wow, how time flies.

As discussed earlier in this thread, I've been working on a new version of lunr that will support highlighting matched terms.

I've finally got round to putting together an [alpha release](https://github.com/olivernn/lunr.js/commit/40140f023923d22575d73cdb1d06b7908ec943a0), as well as an [example](https://olivernn.github.io/moonwalkers/) showing how the highlighting will work.

This is an early alpha release, but should be fairly stable. I wouldn't recommend using it in production yet, but it should be possible to start testing using it, install with `$ npm install lunr@alpha`.

The [example repository](https://github.com/olivernn/moonwalkers) shows how to use this new version, the interface is largely the same as the current version of lunr, but with a few small differences.

Specifically the code for highlighting search terms, which is not part of lunr, is [here](https://github.com/olivernn/moonwalkers/blob/master/src/wrapper.js).

The plan is to get some feedback on this (and other) alpha releases before getting a final release together. The more people who test it out the better.

**Comment by julmot** [comment]
I'm wondering why you've reinvented the highlighting functionality in the wrapper file? There is already e.g. [mark.js](https://markjs.io/) out there which is specifically built for this task. 

You're using `createTreeWalker` with an `acceptNode` property. I [don't think this will work in IE9](http://stackoverflow.com/questions/38245898/createnodeiterator-fails-in-ie9-when-acceptnode-is-specified). mark.js on the other side is heavily cross-browser unit-tested and knows this and further issues.

**Comment by olivernn** [comment]
The wrapper.js script is _an_ example of how to use the data that is now returned by lunr to highlight words. It is by no means intended to be a production ready library that is ready to use out of the box.

I wasn't aware of mark.js, having taken a look at it it seems that it will not be compatible with the results from lunr. Unless I'm mistaken it assumes it will be passed words to highlight, but, as mentioned earlier in this thread, that is something that lunr cannot provide efficiently.

**Comment by olivernn** [comment]
One last thing, lets keep the discussion going in #25 so its all in one place.
