### ISSUE TITLE
tokenizer.seperator should ideally be spelled separator (with an A)

### ISSUE THREAD

**Issue by atamon** [olivernn/lunr.js#206]
Hi,

Thanks for all the great work put into this library. I'm merely creating this issue in hope that it will show up in someones search results if they are as careless as I was.

Today https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L30 reads `seperator`, with a second `e`. Whereas a quick google will tell you that it is more often spelled `separator`, with an `a` in this position.

Ideally, maybe this should be made into a setter function, so as to avoid spelling mistakes on something like this.

Please close as wontfix if this is a nonsense issue for you :)

**Comment by olivernn** [comment]
I _suck_ at spelling! Thanks for the very delicate way you put it also...

> it is more often spelled separator

:laughing: 

As annoying as having something spelled ~~wrong~~ esoterically is, I'd rather not change the name of this, it would be a breaking change, and for something that others are likely to have incorporated into their applications. As far as I know there is no good way of aliasing in JavaScript, though if you can think of a good solution then do let me know.

I'm going to close this for now, just to keep the issues queue slightly more under control, but it is not a nonsense issue.

Thanks,
