### ISSUE TITLE
Store index in MongoDB

### ISSUE THREAD

**Issue by danielflippance** [olivernn/lunr.js#207]
Is there a recommended way/sample code to store the index in MongoDB? Or perhaps you can recommend a fork/repo which adds that capability?

**Comment by olivernn** [comment]
You can serialise a lunr index to JSON which you should be able to store in MongoDB:

```javascript
var idx = lunr(function () {
  // your configuration here
})

var json = JSON.stringify(idx)
```

This will dump the entire index has JSON which you can then store however you need. When the time comes to retrieve the index you can load it like so:

```javascript
var idx = lunr.Index.load(json)
```

lunr requires the entire index to be in memory though, the current implementation will not work with the index stored somewhere else (e.g. MongoDB). It would definitly be possible to adapt the existing implementation to acheive this, but it is not a goal of the project.
