### ISSUE TITLE
Make tokenizer a property of the index (or of a field)

### ISSUE THREAD

**Issue by metmajer** [olivernn/lunr.js#21]
The tokenizr is a static function of the `lunr` instance, which is itself a singleton.
As a result, it is not easily possible to maintain different tokenizers within a single application.

I would be happy to see the tokenizer become a member of `lunr.Index`, or preferably of a `field` (as it is with Solr).

Thanks for lunr.js and regards, Martin

**Comment by mjrussell** [comment]
I know this is an incredibly old issue, but this is a really big limitation right now for us in using lunr. If we have two different sets of documents being searched over, we have to ensure that the global tokenizer gets reset each time to match the docs we are searching. Any updates on this?

**Comment by olivernn** [comment]
Ack, how did I miss this one. I [recently made some changes](https://github.com/olivernn/lunr.js/commit/ab45a589806d866b0f41f4638f9cfc022be555e1) to the tokenizer and didn't remember to take a look through the open issues to see if I could address any other issues at the same time :disappointed: 

I think the right thing to do, for now, is to simply add a property to the instance of `lunr.Index` that points to the existing tokeniser. This should make customising the tokeniser on multiple instances ~~easier~~ possible.

I'm not going to add custom tokenisers per field yet, though I will take that feature into account in a larger upcoming change to the library.

**Comment by mjrussell** [comment]
:+1: for the property on the `Index`. That would easily solve our use case.

Thanks!

**Comment by olivernn** [comment]
I've implemented something in #205 that should hopefully provide the functionality you require.

An example of the usage would be:

```javascript
var myCustomTokenizer = function (obj) {
  // custom tokenising implementation goes here!
}

// registering the tokenizer is only required if the index needs to be serialised using toJSON
lunr.tokenizer.registerFunction(myCustomTokenizer, 'myCustomTokenizer')

var idx = lunr(function () {
  // normal index definition goes here

  this.tokenizer(myCustomTokenizer)
})
```

It would be possible to wrap this up in a plugin also:

```javascript
var myTokenizerPlugin = function () {
  var tokenizer = function (obj) {
    // implementation
  }
  
  lunr.tokenizer.registerFunction(tokenizer, 'myTokenizer')

  this.tokenizer(tokenizer)
}

var idx = lunr(function () {
  this.use(myTokenizerPlugin)
})
```

Anyway, please take a look and try it out and give me your feedback. It'll be great to close a very long running feature request!

**Comment by d0ugal** [comment]
Based on [this comment](https://github.com/olivernn/lunr.js/pull/205#issuecomment-193899936) I think this issue can now be closed.

**Comment by olivernn** [comment]
closing.
