### ISSUE TITLE
disable stemmer and stop words

### ISSUE THREAD

**Issue by simoneggler** [olivernn/lunr.js#212]
i would like to use lunr without stemmer and stop words. there's seems no way to disable this.

**Comment by olivernn** [comment]
You have a couple of choices to remove the stemmer and stop word filtering from an index:

Create the index without these functions; the convinience `lunr` [function sets up some sensible defaults](https://github.com/olivernn/lunr.js/blob/master/lib/lunr.js#L36-L48)
  ```javascript
    var idx = new lunr.Index
    idx.pipeline.add(lunr.trimmer)
  ```

Alternatively, remove these functions from the indexes pipeline
  ```javascript
    var idx = lunr(function () {
      this.pipeline.remove(lunr.stemmer)
      this.pipeline.remove(lunr.stopWordFilter)
    })
  ```

**Comment by ciez** [comment]
how to remove stopwords filter when using lunr.multiLanguage?

thank you kindly
