### ISSUE TITLE
change to idf calculation broken boosting

### ISSUE THREAD

**Issue by johnl** [olivernn/lunr.js#213]
I upgraded from 0.4.x to 0.7.0 and noticed a major difference in my search results. I've narrowed it down to this change in 0.5.10: https://github.com/olivernn/lunr.js/commit/463055f49044d3ef52762a7c8fae86ff3742c28e

I have a large corpus of documents with the fields title and body. The title has a small boost to ensure it's considered more highly, which worked fine before the idf change. But with that idf change, there is no boost parameter high enough for title that can prioritize it correctly.

The words in the title I'm using are very common in the bodies, which I presume is related.

I'll try to put together a test case for this but I thought I'd ticket it in the mean time in case the problem was obvious to someone :)

**Comment by olivernn** [comment]
That's quite an upgrade! You should hopefully see some decent performance gains with the change.

The commit you reference is fixing a bug, IDF is supposed to be inverse _document_ frequency. My guess is that you are witnessing the TF-IDF algorithm trying to account for some very common words.

Without access to the index in question it is difficult to do a lot of investigation to your specific case. That said you can do some digging yourself to try and understand what is happening.

The index has a function called `idf` which you can use to find out what the current IDF value for a term is, make sure the indexes processing pipeline has been called on the term before trying to calculate the IDF.

```javascript
var term = "foo",
    idf = idx.idf(idx.pipeline.run([term])[0])
```

Also, out of interest, what was the value of the title boost you were using, and what value have you tried with the latest version?

Let me know how you get along, I can try and help you tune the results to what you want, but the current behaviour is, I believe, correct.

**Comment by olivernn** [comment]
This seems to be stale, feel free to re-open if you have any updates on the issue.
