### ISSUE TITLE
Could this project support UTF-8?

### ISSUE THREAD

**Issue by yefeiyu** [olivernn/lunr.js#214]
In nandy007's fork, it can support Chinese Words,the dress is https://github.com/nandy007/lunr.js
But it's too old.
Could we add nandy007's fixing?

**Comment by olivernn** [comment]
It seems like the changes in @nandy007's fork are introducing [segment](https://www.npmjs.com/package/segment) into the pipeline, altering the tokenizer (which splits strings into tokens for indexing).

Extracting this out into a language plugin sounds like a good idea, you can see some examples in the [lunr-languages]() project, perhaps the [Japanese language plugin](https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.jp.js) is a good reference point.

A quick google search also brings up @codepiano's [fork](https://github.com/codepiano/lunr.js) which seems to be up to date.

Hopefully that is enough to get you going with a solution.
