### ISSUE TITLE
Blank @license field in lunr.min.js causes jsdoc error

### ISSUE THREAD

**Issue by caraya** [olivernn/lunr.js#217]
Having a blank license field in lunr.min.js causes an error when using Lunr in a JSDoc theme. It also causes confusion as to what license the code is licensed under. 

lunr.js has the same issue.

**Comment by olivernn** [comment]
Oops! Fixed now in the [latest version](https://github.com/olivernn/lunr.js/releases/tag/v0.7.1), thanks for pointing it out to me.
