### ISSUE TITLE
[question] Where is persisted the data ?

### ISSUE THREAD

**Issue by jeromevdl** [olivernn/lunr.js#219]
I can't find in the documentation where is stored the data ? Is it IndexedDB ? or something else ?
Can i use it with a **persistent** db ? Means not indexedDB since we cannot rely on it with the quota limitation and LRU mechanism to clear data when quota exceeded...

**Comment by olivernn** [comment]
Which data do you mean?

The documents that you are indexing can be stored anywhere, lunr doesn't care and doesn't even keep a reference to the original document.

The search index built from the documents isn't persisted anywhere by lunr it is kept entirely in memory. Persisting the index is out of scope for the library, however, there are a number of integration points that would allow you to persist it anywhere you want.

The entire index can be dumped as JSON, this JSON can then be persisted wherever, there are hooks into when documents are added, updated and removed, so you can maintain the persistent version of your index too.

Some completely made up, untested code to demonstrate what is possible:

```javascript
var idx = lunr(function () {
  // index configuration etc
})

// some documents you want to index
documents.forEach(function (document) {
  idx.add(document)
})

// some function that persists the index dump
var persistIndex = function () {
  db.store(JSON.stringify(idx)
}

idx.on('add', persistIndex)
idx.on('update', persistIndex)
idx.on('remove', persistIndex)
```
