### ISSUE TITLE
Soundex and diff - or usage for diacritical signs

### ISSUE THREAD

**Issue by christian-beckmann** [olivernn/lunr.js#221]
How is it possible to include a "soundex" search and "diff" usage for tokens in lunr? 
Perhaps anyone who implemented it till yet?

I wan't to find names like "Music" for "Mušič", wich is nearby it. 

Or are there other possibilities to find even diacritical signs with latin1?

Code for soundex here: [http://rosettacode.org/wiki/Soundex](url)

**Comment by olivernn** [comment]
It should be straightforward to add soundex processing to lunr, you will need to package an implementation of the soundex algorithm as a pipeline function.

A pipeline function is a simple transformation on a given token, so for a soundex it would simply return the soundex of a token.

```javascript
// define a soundex pipeline function
lunr.soundex = function (token) {
  return soundex(token)
}

// register it with lunr.Pipeline, this allows you to still serialise the index
lunr.Pipeline.registerFunction(lunr.soundex, 'soundex')
```

With the function defined you can add it to an indexes pipeline, you probably want to remove the built in stemmer, as I doubt stemming and soundex work well together, though YMMV.

```javascript
idx.pipeline.after(lunr.stemmer, lunr.soundex)
idx.pipeline.remove(lunr.stemmer)
```

The soundex function will then be used when indexing documents, and when searching for documents.

Let me know how you get along with this, and whether you need any help. I'm not super familiar with the implementation of the soundex algorithm, but I think it would be a cool add-on for lunr.

Closing as this _isn't_ something that will live in lunr core, but feel free to re-open if you have any questions etc.

**Comment by christian-beckmann** [comment]
Ok, the soundex function can be found here http://rosettacode.org/wiki/Soundex#JavaScript
The diff calculates a similarity for 0 match and till 4 no match.

`var diff = function(a,b) {
var alength = a.length;
	var res = 0 
	
    for (var i=0; i<a.length; i++) {
        if (a.charAt(i) == b.charAt(i)) {
            res++;
        }
    }

	return res  
}
console.log(diff(soundex('Alex'), soundex('Alexander')))
`

So like @atamon hacked here https://github.com/olivernn/lunr.js/issues/70#issuecomment-187962132 for FuzzySearch, there is an "score" for similarity. 
He used only one field "title" in his index. But how to search for multiple fields with soundex? Or a Fuzzy Search like @atamon used.

Can it a be a feature to directly say, a specific field in the index has a "soundex" or one a "fuzzy" or other?

**Comment by olivernn** [comment]
Currently it is not possible, or easy, to change the way that matching of words in the index is implemented, I'm working on a new version of lunr that _may_ make it easier to extend this, but it doesn't exist yet.

Untill it does, I think you can probably get quite far by just storing the soundex of words in the index, and using the existing term matching. The difference would be that instead of matching on stemmed words, it would be matching on the result of applying the soundex algorithm on the words.
