### ISSUE TITLE
Soundex question

### ISSUE THREAD

**Issue by christian-beckmann** [olivernn/lunr.js#224]
Can you please read on, because I can't repopen a closed issue by my self (read second link).
https://github.com/olivernn/lunr.js/issues/221

http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github#answer-21333938

**Comment by olivernn** [comment]
Closing this, as it isn't something that is going to be implemented soon, feel free to keep the discussion going on the original issue though.
