### ISSUE TITLE
index not unserialized properly

### ISSUE THREAD

**Issue by elelay** [olivernn/lunr.js#228]
calling search on a loaded index throws TypeError.

See this code:
```
var i = lunr(function() {
    this.field('summary')
    this.ref('id')
  });

  i.add({ summary: "hello", id: 1});

  var reference = i.search("hello");

  var j = lunr.Index.load(i.toJSON());

  var res = j.search("hello"); // should not throw
```
It throws `TypeError: this.tokenStore.get(...)[documentRef] is undefined` on `j.search`.

This is because lunr.SortedSet.load is sometimes called with an object having `length: Integer` and `elements: Array` and sometimes with an Array directly.

**Comment by olivernn** [comment]
I'm not sure I understand why `lunr.SortedSet.load` is ever being called with different object structures, they should always be the same?

I *think* the problem with the above code is that you are calling `toJSON` directly, you should be using `JSON.stringify` to serialise the index.

```javascript
  var i = lunr(function() {
    this.field('summary')
    this.ref('id')
  });

  i.add({ summary: "hello", id: 1});

  var reference = i.search("hello");

  var j = lunr.Index.load(JSON.parse(JSON.stringify(i)));

  var res = j.search("hello"); // does not throw
```

The above snippet does not throw errors for me.

**Comment by elelay** [comment]
OK. That's because JSON.stringify will call `toJSON()` on nested values (inside the index.documentStore.elements) automatically, while calling `index.toJSON()` will only execute the code of the function.
See:
```javascript
x = {
    a: [{
        v: "live",
        toJSON: function() {
            return {
                v: "stringified"
            };
        }
    }],
    toJSON: function() {
        return {
            a: this.a
        };
    }
}
```

`x.toJSON()` returns
```javascript
{
    a: [{
        v: "live",
        toJSON: function() {
            return {
                v: "stringified"
            };
        }
    }]
}
```

`JSON.stringify(x)` returns
```javascript
"{"a":[{"v":"stringified"}]}"
```

I'm saving the index to IndexedDB, which is performing a [structured clone](https://html.spec.whatwg.org/multipage/infrastructure.html#structured-clone) of the `index.toJSON()` output, not stringifying it. This is why I hit this case.

Maybe a hint in the documentation that `JSON.stringify()` has to be invoked on the result of `index.toJSON()` would be nice?
Thanks,

**Comment by olivernn** [comment]
Yeah, the project is sorely lacking in any kind of guides around these things, its something I want to do but struggle to find the time.

I'm glad you managed to get this working though!
