### ISSUE TITLE
Examples how to customize  lunr

### ISSUE THREAD

**Issue by anatoly314** [olivernn/lunr.js#230]
Hi,
Maybe it's dumb question but I couldn't realize how to add custom tokenizer to lunr, is it possible? Where can I find more advanced examples? 

Thank you for great library.

**Comment by olivernn** [comment]
It is possible, but probably poorly documented. The feature was [requested](https://github.com/olivernn/lunr.js/issues/21) a long time ago, but I only [added](https://github.com/olivernn/lunr.js/pull/205) it very recently. There is a simple example in the [tests](https://github.com/olivernn/lunr.js/blob/master/test/index_test.js#L34-L42) that might help.

The tokeniser function must split an object (probably a string, but it should handle other object types in some way also) into strings. You can look at the default [tokeniser]() for some inspiration.

Once you have defined your tokeniser you must associate it with the index, like so:

```javascript
var myCustomTokeniser = function () { /* implementation goes here */ }
lunr.tokenizer.registerFunction(fn, 'myCustomTokeniser') // allow the index to be serialised
  
// when creating the index
var idx = lunr(function () {
  this.tokenizer(myCustomTokenizer)
})
```

Alternatively the default tokeniser allows you to [change](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L23-L30) what it considers white space to split on, if that is all you need to change.

Let me know if you have any other questions.

**Comment by olivernn** [comment]
Closing. More [documentation on customising lunr](https://lunrjs.com/guides/customising.html) is also available.
