### ISSUE TITLE
Greek language support for lunr.js

### ISSUE THREAD

**Issue by miljkovicmisa** [olivernn/lunr.js#232]
Is it possible to implement this [greek stemmer](https://github.com/Apmats/greekstemmerjs) in lunr.js? Generally I found the information on implementing a new language support very poor.

_P.S. I'm familiar with only some basics of javascript and am still in learning process._

**Comment by Apmats** [comment]
Copying from the comment I left over here Apmats/greekstemmerjs#1

 I haven't had experience with lunr.js before, but after having a look you can probably override the stemmer used with something like this:

```javascript
var lunr = require('lunr'),
    greekStemmer = require('greek-stemmer');


lunr.trimmer = function trim(word) { return word };
lunr.stemmer = greekStemmer.stem;

lunr.Pipeline.registerFunction(lunr.stemmer, 'stemmer');
lunr.Pipeline.registerFunction(lunr.trimmer, 'trimmer');

var idx = lunr(function () {
  this.ref('id')

  this.field('title', { boost: 10 })
  this.field('author', { boost: 100 })
  this.field('body')
})




var doc = {
    "title": "ΕΝΑΣ ΤΙΤΛΟΣ ΕΔΩ",
    "body": "ΚΑΠΟΙΟΣ",
    "author": "ΕΝΑΣ ΣΥΓΓΡΑΦΕΑΣ",
    "id": 1
}
idx.add(doc);

console.log(idx.search("ΚΑΠΟΙOI"));
```

You also need to override the trimmer as far as I can see, because otherwise all non-latin characters in words are discarded, maybe you will need to make your own that makes sense for greek.


I'm sure someone more familiar with lunr will be able to help you with what exactly you'd have to do for this to be done the proper way though.

**Comment by olivernn** [comment]
The suggestion by @Apmats is pretty much spot on, though you don't need to overwrite the existing stemmer, you can just register a new one:

```javascript
var greekStemmer = require('greek-stemmer').stem
lunr.Pipeline.registerFunction(greekStemmer, 'greekStemmer') // register the greek stemmer so you can serialise/deserialse the index

var idx = lunr(function () {
  this.pipeline.use(greekStemmer) // add the greek stemmer to this indexes pipeline
  this.pipeline.remove(lunr.trimmer) // it doesn't work well with non-latin characters

  this.ref('id')
  this.field('title', { boost: 10 })
  this.field('author', { boost: 100 })
  this.field('body')
})
```

There are multiple examples of language specific extensions to lunr in [lunr-languages repository](https://github.com/MihaiValentin/lunr-languages)

**Comment by olivernn** [comment]
I've also posted an [answer](http://stackoverflow.com/questions/39344299/greek-language-support-for-lunr-js) to your StackOverflow question that goes into some more detail.

**Comment by miljkovicmisa** [comment]
lunr API is not working like you showed me, here is my code, is there a way to debug such things as not registered functions or lunr not getting the registered function at all?  Here is my code, I did everything as you showed me.

`
// the stemmer function

function stemWord(w) {
// some code that stems the word based on the porter algorithm
return w;
}

    // create the pipeline function based on the stemWord function of the greek stemmer

    var greekStemmer = function greekStemmer(w) {
      return stemWord(w);
    }

    // register the pipeline function

    lunr.Pipeline.registerFunction(greekStemmer, 'greekStemmer')

// initialize the index

var idx = lunr(function () {

      // add the new custom function

      this.pipeline.add(greekStemmer)

      // remove the trimmer
      
      this.pipeline.remove(lunr.trimmer)

      this.field('id');
      this.field('title', { boost: 10 });
      this.field('author');
      this.field('category');
      this.field('content');
    });
`

**Comment by miljkovicmisa** [comment]
My code looks like this now and still not stemming the words

`function stemWord(w) {
// code that returns the stemmed word
};

// create the new function
greekStemmer = function (token) {
    return stemWord(token);
};

// register it with lunr.Pipeline, this allows you to still serialise the index
lunr.Pipeline.registerFunction(greekStemmer, 'greekStemmer')

  var index = lunr(function () {
    this.field('title', {boost: 10})
    this.field('body')
    this.ref('id')

    this.pipeline.remove(lunr.trimmer) // it doesn't work well with non-latin characters
    this.pipeline.add(greekStemmer)
  })

    index.add({
    id: 1,
    title: 'ΚΑΠΟΙΟΣ',
    body: 'Foo foo foo!'
  })

  index.add({
    id: 2,
    title: 'ΚΑΠΟΙΕΣ',
    body: 'Bar bar bar!'
  })


  index.add({
    id: 3,
    title: 'ΤΙΠΟΤΑ',
    body: 'Bar bar bar!'
  })`

**Comment by olivernn** [comment]
I'm guessing that you are expecting two results, document 1 and 2?

I *think* I see the problem, it looks like the greek stemmer expects the words to be in upper case, however, lunr converts [everything to lower case](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L20). I managed to get your example working by changing the `greekStemmer` function to this:

```javascript
greekStemmer = function(word) {
  return stemWord(word.toUpperCase()).toLowerCase();
};
```

**Comment by miljkovicmisa** [comment]
Ow boy! I didn't know that lunr does this, I knew though that my stemmer required uppercase because lowercase Greek is too complicated to stem because of all the variations that are produced by accents. Thank you very much for your support!

**Comment by olivernn** [comment]
Yeah, a tricky one to figure out! If you get the time, I highly recommend putting the pieces you have together into a some kind of repo here on github, these kind of undocumented things are otherwise too easy to forget/lose. Code is more permanent.

If you have any other problems let me know!
