### ISSUE TITLE
search with single letter matches start of words

### ISSUE THREAD

**Issue by jbouzekri** [olivernn/lunr.js#234]
This is a kind of "help wanted" issue. I have a lunr instance where I index computer science articles. There are some talking about the language C or R. Is it possible to have lunr only return articles with the letter C or R as a word ? Right now it returns all articles having words starting with these letters.

Or another use case, if i search c++, the "++" seems to be trimmed.

**Comment by olivernn** [comment]
The current version of lunr automatically inserts a wildcard at the end of every search term, e.g. a search for "c" is actually treated like "c*" in lunr. There is no way to disable this. The next version of lunr will give you more control over how searches are performed, but its not quite ready yet...

There are a couple of work arounds that you might consider in the meantime though. You _could_ add a pipeline function to alter the way these terms are indexed and searched. Something like this:

```javascript
var programmingLangFilter = function (word) {
  if (word == "c" || word == "r") {
    return word + "lang"
  } else {
    return word
  }
}

var idx = lunr(function () {
  // normal index definition
  this.pipeline.add(programmingLangFilter)
})
```

This might make it easier to search for these single letter languages. The above is a very basic implementation, but should hopefully point you in the right direction.

As for the trimmer, it will indeed chop off the "++" as you mention. You could solve this in a similar way as mentioned above, maybe converting "c++" to "cplusplus", keep in mind that the trimmer is the [_first_ function in the default pipeline](https://github.com/olivernn/lunr.js/blob/master/lib/lunr.js#L39-L43). Alternatively you could try completely removing the trimmer.

**Comment by jbouzekri** [comment]
Very clear explanation.Thanks @olivernn

**Comment by olivernn** [comment]
Hopefully it helps, I'll close this issue now, but will update when there is a better solution, i.e. the next major version of lunr.
