### ISSUE TITLE
I'm not sure this is intended but it causes crash when having results > 2

### ISSUE THREAD

**Issue by FocuzJS** [olivernn/lunr.js#235]
If I have more than 2 matching the search it breaks everything

**Comment by FocuzJS** [comment]
I know it's a vague description, but it's definately the lib

**Comment by olivernn** [comment]
To observe lunr not breaking everything with more than 2 matching (I guess you mean results) take a look at the [example](http://lunrjs.com/example/), try searching for "jquery" or "javascript".

Unless you can provide some more detail, ideally an actual reproduction, then there is nothing I can do to help.

**Comment by olivernn** [comment]
Without any further details I can't help you, feel free to open an issue with an actual error message and reproduction and I'll take a look.
