### ISSUE TITLE
Look for sub string match not working

### ISSUE THREAD

**Issue by gkorland** [olivernn/lunr.js#238]
The document we index looks like this
`
{
    id: 12,
    barcode: "1234567"
}
`

The search looks like this

`
idx.search("012345678")
`

But it doesn't find the document, is there a way to have a contains query?
e.g. 
`
SELECT * FROM products WHERE '012345678' LIKE '*' + barcode + '*'
`

**Comment by olivernn** [comment]
The [latest](https://github.com/olivernn/lunr.js/releases/tag/v2.0.1) version of Lunr does offer more support for wildcards when searching.

In your example I think using fuzzy matching may be preferable, e.g.

```javascript
idx.search("barcode:012345678~2")
```

There is more detail in the search [documentation](https://lunrjs.com/guides/searching.html#fuzzy-matches)
