### ISSUE TITLE
How do I index email addresses?

### ISSUE THREAD

**Issue by CrescentFresh** [olivernn/lunr.js#245]
Apologies for the silly question, how do I get lunr to index email addresses? The default behavior seems to index only the first part of the address before the @ symbol.

Examp:

    var s = lunr(function() {
        this.field('email');
        this.ref('id');
    });

    s.add({ id: 123, email: 'foo@bar.com' });

    s.search('foo'); // 1 hit
    s.search('bar'); // 0 hits
    s.search('com'); // 0 hits

Is there some customization to the tokenizer I can add to allow splitting apart email addresses into their constituent parts for the indexer to recognize?

**Comment by olivernn** [comment]
You _can_ do this by altering how a string is split into tokens, the [`lunr.tokenizer.separator`](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L43-L50) property is what you need to modify to do this.

I think splitting the email address into the parts you want individually indexed may be a better approach though. Depending on your use case you could either have two fields (local and domain) or represent the email field as an array of local and domain

```javascript
{
  id: 123,
  emailLocal: 'foo',
  emailDomain: 'bar.com'
}

{
  id: 123,
  email: ['foo', 'bar.com']
}
```

Having them split out allows a boost to be applied to either the local or the domain part of an email address.

I guess the thing to remember is that the documents that you add to the lunr index don't nesecarily have to be the raw documents that just contain text, you can perform more specific transforms on them before indexing them in lunr.
