### ISSUE TITLE
Question: Is it possible to add entries to, or remove entries from, the index?

### ISSUE THREAD

**Issue by tashburn** [olivernn/lunr.js#259]
In the docs, I can't seem to find a way to add and remove entries to the index without rebuilding it in its entirety. I really need this feature. Is this possible?

**Comment by olivernn** [comment]
Short answer: no.

This is the largest change in version 2 of Lunr. Initially I was hesitant about going in this direction (i.e. indexes being immutable) but ultimately I think it is the right decision. By not allowing index mutations the internal data structures are much simplified and allow for some more interesting features. In addition the performance also gets a boost, both in index size, and query time. Finally, the majority of use cases for Lunr were for searching largely static data, think static sites etc.

I know thats probably not the answer you wanted 😞

I'm not ruling out allowing adding/removing from indexes (in some form) in the future, but it isn't a priority at the moment. The 1.x versions of Lunr _do_ support adding and removing documents from an index and they will continue to receive bug fixes etc so you start there if you still want to use Lunr.

**Comment by tashburn** [comment]
Thanks for the explanation. I'm bummed though. I'll have to pick something else. My additions and removals to the index would be too frequent to rebuild the entire index regularly and suffer the ram/cpu hit. I'm reluctant to use the old version of lunr. Any suggestions beyond that?

**Comment by olivernn** [comment]
Yeah, sorry about that, I knew it would probably prevent a few people from being able to use Lunr 2, but, on balance, I still think it was the right decision.

Any reason you can't use Lunr 1.x series, are there any specific features that it is missing that you can't live without?

As for alternatives, I don't have enough experience with any other JS search libs to be able to recommend one. If you do find something worth while using then please update this issue so others can benefit from your research.

**Comment by tashburn** [comment]
I'll look at Lunr 1.x. My reservations are not specific to it, but generally that old versions of software usually are on a downward trend of reduced investment, support, and improvements.

**Comment by meltuhamy** [comment]
@olivernn I also prefer the idea of adding to an index at run time, especially that client side search is being used more frequently in SPAs which are long-lived. 

However, I'm interested to see what the performance improvements of indexing are? Did you measure and compare them between v1 and v2? Thanks!

**Comment by olivernn** [comment]
@meltuhamy I did testing during development and search performance was roughly an order of magnitude faster, while serialised index size was ~10% smaller. Really though the biggest gains from being immutable are in the additional search features that are capable by using data structures that are immutable.

As I said to @tashburn the v1 branch is stable and does support adding/removing documents from an index. It's probably fast enough (it was heavily optimised over several years), it's just unlikely to get any faster without the kind of changes already existing in v2.

**Comment by meltuhamy** [comment]
Thanks for your reply @olivernn

**Comment by alex-at-oclc** [comment]
Following this API change, it wasn't clear to me how to asynchronously walk a tree of docs and add them to the index without loading them all in to memory up-front - it seems more geared towards building the index in a synchronous block. I'm not sure whether there is a better approach, but my solution was just to unpick the lunr() function, including here in case this helps anyone:

```js
    const walker = walk.walk(srcPath);
    var builder = new lunr.Builder

    builder.pipeline.add(
      lunr.trimmer,
      lunr.stopWordFilter,
      lunr.stemmer
    )

    builder.searchPipeline.add(
      lunr.stemmer
    )

    builder.field('doc');

    walker.on('file', (root, stats, next) => {
      const inputFile = path.join(root, stats.name);
      const relativePath = root.substr(srcPath.length);
      const outputPath = path.join(buildPath, 'content', relativePath);

      const filename = stats.name.slice(0, -3);
      const outputFile = path.join(outputPath, filename + '.js');
      const url = path.join(relativePath, filename);
      const doc = fs.readFileSync(inputFile, 'utf8');
      builder.add({ doc })
     
      next();
    });

    walker.on('end', () => {
      const index = builder.build()
      const indexFile = path.join(buildPath, 'static', '_index.json');
      fs.mkdirpSync(path.join(buildPath, 'content'))
      fs.writeFile(indexFile, JSON.stringify(index.toJSON()), 'utf8');
    })
```

**Comment by olivernn** [comment]
@alex-at-oclc that is a perfectly valid solution, the `lunr()` function is just a convenience for quickly setting up indexes. As you've seen the [`lunr.Builder`](https://lunrjs.com/docs/lunr.Builder.html) class is the main thing responsible for doing the hard work of building an index and it is perfectly acceptable to interact with it manually.
