### ISSUE TITLE
Is there a way to search by two fields?

### ISSUE THREAD

**Issue by exequeryphil** [olivernn/lunr.js#265]
I'm thinking of a situation like this:

```var results = idx.search('year:2009 category:api');```

But that isn't working.  I basically want to find all 'posts' by two criteria.  If there is a way to do this, maybe you could point me toward an example somewhere?

**Comment by olivernn** [comment]
What do you mean by "isn't working"? Is there an error or are you not getting the results you expect? If so what were you expecting and what did you get?

**Comment by olivernn** [comment]
Closing this now, please feel free to re-open or cut a new issue if you have more details, or any other problems.
