### ISSUE TITLE
How to escape a special character?

### ISSUE THREAD

**Issue by meltuhamy** [olivernn/lunr.js#271]
e.g. Is it possible to search for the character '^' using the search method? I do not want it to be interpreted as a search modifier (boost).

**Comment by olivernn** [comment]
At the moment the search string does not provide support for escaping characters. This is something that I want to add at some point.

In the mean time you can use [`lunr.Index#query`](https://lunrjs.com/docs/lunr.Index.html#query) directly to perform a search with a '^' character:

```javascript
idx.query(function (q) {
  q.term("foo^")
})
```

**Comment by meltuhamy** [comment]
Thanks @olivernn , I actually looked at that before but then I was stuck trying to get the best of both worlds, e.g. `title:n^2`. Any ideas as to how I can do this?

**Comment by olivernn** [comment]
Everything that is possible with a search string is possible with the `lunr.Index#query` method, `lunr.Index#search` is implemented on top of it.

```javascript
idx.query(function (q) {
  q.term("n^2", { fields: ["title"] })
})
```

The [documentation](https://lunrjs.com/docs/lunr.Query.html) shows how to add fields, boosts etc.

**Comment by meltuhamy** [comment]
great, thanks @olivernn . Do you know how I can escape the wildcard `*` character? `q.term('*')` does a wildcard search...

**Comment by olivernn** [comment]
Its not possible to escape the wildcard character at the moment, and I think it'll be a bit tricky to implement. I'll think about the best way to do so when implementing escape sequences in the search string, but "*" has special meaning in a number of places that might be harder to sidestep.

**Comment by olivernn** [comment]
The latest alpha (2.1.0-alpha.2) includes support for escape query characters, e.g "12\:00pm" will do a search for "12:00pm" rather than complain about a missing field called "12".

This does not include support for escaping asterisks "*", that requires some more fundamental changes that I'm not inclined to work on, yet.

As ever, try it out and let me know any feedback.

**Comment by olivernn** [comment]
I've just published 2.1.0 which includes support for escaping special characters.

**Comment by jeckep** [comment]
Excuse me, but I couldn't find the instruction how to use escaping for special charactes, could you please point me. 

I try to search term "C#". But 
```js
idx.query(function (q) {
  q.term("C#")
});
```
didn't work.
I am also searching for possibility to search terms with characters: ":", "."  

Thank you.

**Comment by wangpin34** [comment]
I cannot find any instruction about escaping the modifiers as well. @olivernn Any updates? thanks.

**Comment by wereHamster** [comment]
@wangpin34 I found this in our code, not sure where I got it from:

```js
str.replace(/[~^\-+]/g, (x) => `\\${x}`)
```
