### ISSUE TITLE
`termFrequencies` hash does not support "special" terms such as `constructor`

### ISSUE THREAD

**Issue by petebacondarwin** [olivernn/lunr.js#280]
I think this hash lookup is being created as `{}` but should be created as `Objecte.create(null)` to ensure that the object has no unwanted prototype properties.

**Comment by petebacondarwin** [comment]
In particular this line here: https://github.com/olivernn/lunr.js/blob/789aa68c375278e38127451da6a2699f98fc5a3c/lib/builder.js#L128

But in general all usage of `{}` for hashes that might have user defined keys should be using `Object.create(null);`

**Comment by petebacondarwin** [comment]
It seems that this was partially addressed in https://github.com/olivernn/lunr.js/commit/d624a2c25a5884cb4c0a5c36b4df361bfd58ae05 but it did not fix the `termsFrequencies` hash.

**Comment by olivernn** [comment]
I've just pushed version 2.1.1 which includes your fix for this issue, thanks again for taking the time to report, and fix, the bug!

**Comment by petebacondarwin** [comment]
Great!
