### ISSUE TITLE
Mention lunr-languages in README and docs

### ISSUE THREAD

**Issue by shamrin** [olivernn/lunr.js#288]
It looks like [lunr-languages](https://github.com/MihaiValentin/lunr-languages) is [*the* way][2] to index non-Engish content witn Lunr.js.

Unfortunately it was not easy to figure it out. And there are distractions: [lunr.ru.js repo][3], #16, #42.

It would be very helpful if the README file and documentation would mention and recommend lunr-languages for non-English search.

(By the way, is there a source code for the documentation on lunrjs.com website?)

[2]: https://github.com/olivernn/lunr.js/issues/197#issuecomment-176411637
[3]: https://github.com/olivernn/lunr.ru.js

**Comment by olivernn** [comment]
Good point, I've been meaning to do this for a while now, just haven't got round to it.

I've put together a [PR](https://github.com/olivernn/lunr-site/pull/2) with a guide on using lunr-languages, please check it out and let me know if there is anything else that would be useful to have.

**Comment by shamrin** [comment]
@olivernn thank you! I've made a couple of comments to the PR.

**Comment by olivernn** [comment]
Deployed, it might take a few hours for the changes to propagate.
