### ISSUE TITLE
Searching multiple terms on multiple fields with different boost using Index.query

### ISSUE THREAD

**Issue by myalgo** [olivernn/lunr.js#289]
I would like to know to write the search query efficiently for searching multiple terms on multiple fields with different boost

I have set of fields 

- title with boost 10
- heading with boost 5
- text with boost 3
- keywords with boost 6

and would like to search "foo bar" or "foo bar*"

Since build time boost is not supported in 2.1.2, I am using query time boost.
However would like to use to search with and without trailing wildcard
and with/without usepipeline to get the best results.

Please let me know an efficient way to write query using Index.query or Index.search.

**Comment by jakeapeters** [comment]
You could use something like this (tested in `2.1.0`):

```javascript
const query = 'foo bar';
const idx = ...;
const matches =  idx.query(q => {
    q.term(query, { fields: [ 'title' ], boost: 10 });
    q.term(query, { fields: [ 'heading' ], boost: 5 });
    q.term(query, { fields: [ 'text' ], boost: 3 });
    q.term(query, { fields: [ 'keywords' ], boost: 6 });

    q.term(query, { fields: [ 'title' ], boost: 10, wildcard: lunr.Query.wildcard.TRAILING });
    q.term(query, { fields: [ 'heading' ], boost: 5, wildcard: lunr.Query.wildcard.TRAILING });
    q.term(query, { fields: [ 'text' ], boost: 3, wildcard: lunr.Query.wildcard.TRAILING });
    q.term(query, { fields: [ 'keywords' ], boost: 6, wildcard: lunr.Query.wildcard.TRAILING });
  });
});
```

You can add `usePipeline: false`, `editDistance: ...` etc. as normal inside there. We're using something similar in production.

**Comment by olivernn** [comment]
What @jakeapeters has looks good, one thing to be careful of though is that the `query` string passed to `q.term` will not be split into multiple tokens by lunr. I.e. if `query` is the string "foo bar" it will search for "foo bar" _not_ "foo", "bar", with the default index builder this will mean you won't get any results.

You can borrow Lunr's [tokenizer](https://lunrjs.com/docs/lunr.html#.tokenizer), or use the [regex](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L57-L64) it uses directly:

```javascript
idx.query(function (q) {
  lunr.tokenizer(queryString).forEach(function (token) {
    q.term(token.toString(), { fields: [ 'title' ], boost: 10 })
    // etc....
  })
})
```

or, just borrow the regex:

```javascript
idx.query(function (q) {

  queryString.split(lunr.tokenizer.separator).forEach(function (term) {
    q.term(term, { fields: [ 'title' ], boost: 10 })
    // etc....
  })
})
```

**Comment by myalgo** [comment]
thanks @jakeapeters  and @olivernn.

**Comment by myalgo** [comment]
@olivernn , do you plan to support build time boost?

**Comment by olivernn** [comment]
@myalgo please open a new issue requesting build time boost.

I'm going to close this issue now as I think the original problem is solved.
