### ISSUE TITLE
Usage documentation for Angular 2/4

### ISSUE THREAD

**Issue by kchiragowni** [olivernn/lunr.js#292]
Hello,

I wanted to know if anybody have implemented lunr.js library in Angular 2/4 app. If yes can you provide some information on usage documention.

Many thanks

**Comment by olivernn** [comment]
I don't know Angular, so I can't offer any advice here. You might want to try a question on StackOverflow, there is a [lunr tag](https://stackoverflow.com/questions/tagged/lunrjs) as well as the [angular tag](https://stackoverflow.com/questions/tagged/angular), you might get some more responses there, plus internet points!

**Comment by olivernn** [comment]
I just saw this [article](https://medium.com/codedotgov/a-solar-eclipse-and-the-story-of-adding-a-lunr-js-powered-search-to-code-gov-66c58078e726) which has some steps on getting a lunr index set up with Angular 2, might be useful.

**Comment by kchiragowni** [comment]
Thanks @olivernn I will look into it.
