### ISSUE TITLE
Search (or add) not working.

### ISSUE THREAD

**Issue by mnemanja** [olivernn/lunr.js#298]
Hello,
I'm following the tutorial from this book https://www.manning.com/books/cross-platform-desktop-applications.

They are using the old API, so I've tried using the new one but it does not work for me.

I cannot confirm if search and add exist from the perspective of API.
![image](https://user-images.githubusercontent.com/1423218/30661648-f7a96190-9e44-11e7-9f9f-1dc3e91abc0c.png)
I'm not sure how to debug it. Any thoughts?

```
const lunr = require('lunr');
let index;

function resetIndex() {
  index = lunr(function () {
    this.field('file');
    this.field('type');
    this.ref('path');
  });
}

function addToIndex(file) {
  // The file is an object
  index = lunr(function () {
    this.field('file');
    this.field('type');
    this.ref('path');

    this.add(file);
  });
}

function find(query, cb) {
  if (!index) {
      resetIndex();
  }

  const results = index.search(query);
  // The results returns an empty array [] at this point
  cb(results);
}
```

**Comment by olivernn** [comment]
It looks like you are using Lunr 2.x which no longer supports adding documents to an index _after_ it has been built (more info in the [upgrading](https://lunrjs.com/guides/upgrading.html#index-building) guide).

That said it looks like you are working around this by rebuilding the index every time you want to add a file to it. At a glance it looks like you call `resetIndex` before doing the search, which doesn't actually add any files to the index. I *think* the problem then is in how you are creating the index before searching, you would need to ensure that _all_ the files you want to search are being added to the index.

You can help debug the issue by checking if the index is empty in you `find` function:

```javascript
index.tokenSet.toArray()
```

The above will return all the words that are in the index, if this is empty the either you didn't add anything to the index when building it, or the field object you did add to the index had no words.

Hopefully this helps you get to the bottom of the problem, let me know if you manage to come good on this.

P.S. Paul was a colleague of mine when I worked in London, great guy. Hope you are enjoying his book!

**Comment by mnemanja** [comment]
Thanks for your response.
I'll close this issue since I'm no longer working on this.
