### ISSUE TITLE
Using lunr languages 

### ISSUE THREAD

**Issue by myalgo** [olivernn/lunr.js#302]
I was checking the language support code on https://lunrjs.com/guides/language_support.html
I had following questions :

1) How do I use lunr languages for prebuilt indexes ? Please give example of client side javascript code

2) Does lunr languages support current codebase for lunr? We are currently using 2.1.3

3) Currently languages supported is needed for Japanese, Portuguese, Korean, Chinese (traditional and simplified). However I see only the first 2 languages listed. 

Kindly advice. Thanks!

**Comment by olivernn** [comment]
> How do I use lunr languages for prebuilt indexes ? Please give example of client side javascript code

What did you try? I think this exact scenario is mentioned in the [README](https://github.com/MihaiValentin/lunr-languages/blob/master/README.md) for the lunr languages project.

> Does lunr languages support current codebase for lunr? We are currently using 2.1.3

Yes, it supports every version of Lunr from 0.6 upwards. It looks like the README could be updated here, why not send a pull request?

> Currently languages supported is needed for Japanese, Portuguese, Korean, Chinese (traditional and simplified). However I see only the first 2 languages listed.

If a language you need is not currently supported then there is a [guide](https://github.com/MihaiValentin/lunr-languages/blob/master/CONTRIBUTING.md#i-want-to-add-a-new-language) on adding support.
