### ISSUE TITLE
Documentation: Issue in example Code for Pre-building Indexes

### ISSUE THREAD

**Issue by stjosh** [olivernn/lunr.js#307]
Hi, I hope this is the correct place to post an issue on https://lunrjs.com/guides/index_prebuilding.html .

In the sample node script for building an Index, `var documents = JSON.parse(buffer.join())` is used to parse STDIN to a JSON array. However, this does not work for large inputs (i.e., in case the buffer has more than one element), because if called without arguments, `join()` will join the array elements with a comma separator, resulting in invalid JSON. So, correct is: `var documents = JSON.parse(buffer.join(''))`

Many thanks for correcting this.

**Comment by olivernn** [comment]
The website is in this [repository](https://github.com/olivernn/lunr-site), please open an issue there, or better yet send a pull request ;)

**Comment by olivernn** [comment]
The specific page is https://github.com/olivernn/lunr-site/blob/master/source/guides/index_prebuilding.html.md

**Comment by stjosh** [comment]
Perfect, I was looking for the repo of the site but did not find it - shame on me. :smile: Will open a pull-request!

**Comment by olivernn** [comment]
No problem, thanks for taking the time to open an issue _and_ provide a fix!

**Comment by stjosh** [comment]
See olivernn/lunr-site#3
