### ISSUE TITLE
Add the search term to the output results

### ISSUE THREAD

**Issue by LorenzoSerino** [olivernn/lunr.js#310]
Hi Oliver, 
    I'm trying to add the search term on the results to analyze the result of the output and reject the little significants. For example, I would like to look for the documents containing two clauses:
- first is [po*] (to find the documents with the words beginning with "po".
- the second word is a complete word [topolino]

Now I want to look for all the documents that contain:
- [topolino] and [po*]
- [topolino]
but I dont want,in the results, the documents with a single clause [po *].

On the query, i use:

		var results=idx.query(function (query){
			query.term("topolino", {fields: ["docs"], boost: 100, usePipeline: true })								
			query.term("pa", {fields: ["docs"], boost: 80, usePipeline: true, wildcard: lunr.Query.wildcard.TRAILING})
		});

Then i modified "lunr"
		lunr.Index.prototype.query = function (fn) {
		..
		..
		..
		 for (var l = 0; l < matchingDocumentRefs.length; l++) {
            /*
             * All metadata for this term/field/document triple
             * are then extracted and collected into an instance
             * of lunr.MatchData ready to be returned in the query
             * results
             */
            var matchingDocumentRef = matchingDocumentRefs[l],
                matchingFieldRef = new lunr.FieldRef (matchingDocumentRef, field),
                documentMetadata, matchData

            documentMetadata = fieldPosting[matchingDocumentRef]
			/* MOD START */
			documentMetadata.clauses=[];
			documentMetadata.clauses.push(clause);
			/* MOD END */
            matchData = new lunr.MatchData (expandedTerm, field, documentMetadata)
			
            if (matchingFieldRef in matchingFields) {			  
				matchingFields[matchingFieldRef].combine(matchData)
            } else {
              matchingFields[matchingFieldRef] = matchData
            }
			..
			..

N.B.: the good work is made by "combine".

Now in the metadata item there are the clauses so i can reject the little significants ([po*]) with a loop.

Is there a better method without modifying lunr? 

Regards
	lorenzo

**Comment by olivernn** [comment]
So, it looks like you want to do a query for documents that contain terms matching "topolino" and optionally "po*".

Unfortunately this isn't something that is supported yet in Lunr. It is a much requested feature, and is what I'm currently working on. I've [discussed](https://github.com/olivernn/lunr.js/issues/264#issuecomment-337480632) how I think this should look, but I would phrase that query as:

documents _must_ contain "topolino" and _optionally_ contain "po*", or with the proposed additions to the search syntax: `+topolino po*` or, updating the query you mention in your description:

```javascript
var results=idx.query(function (query){
  query.term("topolino", { fields: ["docs"], boost: 100, presence: lunr.Query.presence.REQUIRED })
  query.term("pa", { fields: ["docs"], boost: 80, wildcard: lunr.Query.wildcard.TRAILING })
});
```

Note that the above syntax might change slightly, but that is what I'm currently aiming for. Would that allow you to write the queries you want?

**Comment by LorenzoSerino** [comment]
Hi Oliver, thanks for the quick reply

I read the old discussed and Yes, your proposal for me is correct.  

if i can i want to help you and i suggest you:
1) lunr.Query.presence.REQUIRED ok
2) lunr.Query.presence.ONLYONE (max 1)

then, more immediate and simple solution  i would add the clause in the items result o a custom function (output pipeline...) for whatever you want.

Thanks in advance
Lorenzo

**Comment by olivernn** [comment]
I'm going to close this as I _think_ it is mostly covered by the 2.2.x release.
