### ISSUE TITLE
Unable to perform search using Cyrillic chars

### ISSUE THREAD

**Issue by x1unix** [olivernn/lunr.js#318]
Lunr.js can't work with collections that contain values with cyrillic characters.

Bug example you can find at [this codepen](https://codepen.io/cyberd/pen/YELwOz)

**Comment by hoelzro** [comment]
@x1unix Привiт!  The default pipeline is English-specific; you may want to check out https://lunrjs.com/guides/language_support.html for other languages.  Unfortunately, it doesn't look like there's a Ukrainian plugin, but maybe you could create one!

**Comment by x1unix** [comment]
@hoelzro, thank you!
