### ISSUE TITLE
tokenizer.separator access modifier in type definition  

### ISSUE THREAD

**Issue by JeremyTCD** [olivernn/lunr.js#323]
@seantanly First off, thanks for the lunr type definitions. Unfortunately, I ran into a minor issue with `tokenizer.separator`:  

```ts
import * as lunr from 'lunr';
lunr.tokenizer.separator = /[\s\-\.]+/;
```
causes the following typescript error:
```
[ts] Cannot assign to 'separator' because it is a constant or a read-only property.
const tokenizer.separator: RegExp
```
Is the [separator property](https://github.com/seantanly/DefinitelyTyped/blob/6802db8a62e53e8f86be567c2420a57eb4620d80/types/lunr/index.d.ts#L813) meant to have a `const` access modifier? If so, is there a way to assign to it?

**Comment by seantanly** [comment]
Thanks for pointing out the error in the type definition. I have submitted a PR to correct this and it should be available soon.

**Comment by seantanly** [comment]
@JeremyTCD the PR is merged and the updated type definition is available now. Do close this issue if it's working for you now. :)

**Comment by JeremyTCD** [comment]
Thanks for the fix! I came across a second issue though, I think the `generateStopWordFilter` function in the `lunr` namespace is missing. I'm not too familiar with typescript but I think the declaration would be something like this:

```ts
function generateStopWordFilter(stopWords: string[]) : PipelineFunction;    
```

**Comment by seantanly** [comment]
@JeremyTCD You're correct with the missing definition. 👍  Added another PR for it. Thanks for making the definition more accurate and complete.

If you may wish to put up a PR for lunr directly on DefinitelyTyped next time too :) in case I'm not available to do so.

**Comment by JeremyTCD** [comment]
@seantanly Thanks again dude. Wasn't super confident in my TS skills :grinning:, but will create my own PRs for future issues. Closing this thread.
