### ISSUE TITLE
Lunr does not support Arabic!

### ISSUE THREAD

**Issue by AhmadIbrahiim** [olivernn/lunr.js#325]
We're  building a solution based on **lunr**  but it seems to be only support Latin characters is there is any solution hack this  .

**Comment by hoelzro** [comment]
Hi @AhmadIbrahiim! I don't have any experience with Arabic, but I chimed in on [this issue](#318) about using lunr with Cyrillic characters.  I don't see a plugin for Arabic listed on https://lunrjs.com/guides/language_support.html, but maybe you could create one!

**Comment by mootari** [comment]
> but I chimed in on this issue

Because the link is broken: The issue is #318.

**Comment by olivernn** [comment]
There is already an [issue](https://github.com/MihaiValentin/lunr-languages/issues/9) on the lunr-languages project for adding Arabic support. My guess is that you will get more traction by providing a pull request than an issue however.

Either way this is not an issue in Lunr, it _could_ support Arabic if someone would put together a [language plugin](https://lunrjs.com/guides/language_support.html) for it.
