### ISSUE TITLE
Feature Request : Use of Tokenizer without indexing

### ISSUE THREAD

**Issue by kapilgupta77** [olivernn/lunr.js#333]
Hi,

Is it possible to just use tokenizer to tokenize a string? Currently, I have to first create an index and then use  index.tokenSet.toArray() to get a list of unique words in an array.

Thanks
Kapil

**Comment by olivernn** [comment]
It is possible to use [`lunr.tokenizer`](https://lunrjs.com/docs/lunr.html#.tokenizer) without first creating an index:

```javascript
var tokens = lunr.tokenizer("some string")
```

> then use index.tokenSet.toArray() to get a list of unique words in an array

`lunr.tokenizer` does not return a unique list of words though, it just converts a string into tokens, there may be duplicates:

```javascript
lunr.tokenizer("foo foo foo").length // 3
```

You could certainly use [`lunr.TokenSet`](https://lunrjs.com/docs/lunr.TokenSet.html) to get a unique set of the tokens returned by `lunr.tokenizer` but I'm sure you can think of [a simpler way without having to use Lunr](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).

**Comment by kapilgupta77** [comment]
Thank you Oliver.
