### ISSUE TITLE
Search on field with AND 

### ISSUE THREAD

**Issue by miraks31** [olivernn/lunr.js#344]
As documented (https://lunrjs.com/guides/searching.html):
- we must use something like 'tags:foo' if we want to search on field 'tags'.
- we must use '+foo +bar' if we want to search 'foo' AND 'bar'

I would like to search all documents having 'tags:foo' AND containing 'bar'.
I tried:
- 'tags:foo +bar' ==> WRONG result (Applied as a OR)
- 'tags:+foo +bar' ==> WRONG result (no result, may be because +foo is not a tag)
- '+tags:foo +bar' ==> SYNTAX ERROR (unrecognised field '+tags', possible fields: 'text', 'title', 'tags')

How should I do?
Is it a bug.

**Comment by olivernn** [comment]
First, check what version of Lunr you are using, term presence queries are only supported in version 2.2 and up.

Second, I _think_ there might be a bug, you can try this out on the [demo site](https://olivernn.github.io/moonwalkers/):

Searching for documents with alan AND skylab: `+alan +skylab` returns just one result, this is correct. Restricting the term "alan" to the name field does not seem to work, the presence modifier seems to get ignored: `+name:alan +skylab` returns three results.

I'll take a closer look at this, thanks for reporting.

**Comment by miraks31** [comment]
Thank you for this quick answer.
For your information, I'm using lunr 2.1.5 (the version installed by npm install).
Regards.

**Comment by olivernn** [comment]
Yeah, 2.1.5 does not have term presence support, you will need to upgrade to 2.2.0 to get term presence support.

**Comment by miraks31** [comment]
I successfully installed Lunr 2.2.0.

**Comment by olivernn** [comment]
I've just pushed 2.2.1 with a fix for the bug that caused the issues mentioned here, please take a look and let me know if you run into problems.

**Comment by miraks31** [comment]
Hi,

This works well. 
Thank you for this VERY VERY fast correction !
