### ISSUE TITLE
Lower level query interface

### ISSUE THREAD

**Issue by olivernn** [olivernn/lunr.js#37]
A more advanced query interface is something that lunr definitely needs. I'm not entirely sure what the interface would look like for this, perhaps a different method on the index and a query object itself:

```
idx.query(function () {
    this.all('foo bar*') // these are AND query terms
    this.some('*baz') // these are OR query terms

    this.limit(10) // maximum number of results to return
    this.threshold(0.7) // minimum score for returned documents

    this.facet('herp', ['derp', 'burp']) // facets and values
})
```

This is just a very rough idea, but I think it is the right direction. It hopefully exposes a more powerful interface to the search. The `idx.search` method would still exist as a quick way to perform searches, but it would probably be built onto of this query method.

Any input or feedback is much appreciated.

**Comment by KyleAMathews** [comment]
+1

**Comment by Prieul-Simon** [comment]
I agree with this one. OR based queries are what I need. For now, i used the same trick as the one described [here](https://github.com/olivernn/lunr.js/pull/36)

**Comment by olivernn** [comment]
It turned out differently the described in this issue, but the latest version of Lunr does provide more control over [performing queries](https://lunrjs.com/guides/searching.html).
