### ISSUE TITLE
upgrading lunr in hugo?  

### ISSUE THREAD

**Issue by avonlea** [olivernn/lunr.js#371]
[Hugo](https://gohugo.io/), the static site generator, comes with lunr 0.7.2.  

I tried upgrading to lunr 2.3.2.  I created the index differently as described in the [getting started - upgrading page](https://lunrjs.com/guides/upgrading.html).  

I'm not able to get search to work though.  

I can't even get the very simple index/search('bright') example given in the [getting started page](https://lunrjs.com/guides/getting_started.html) working for my website.  

I'm not sure how to start debugging this.

**Comment by avonlea** [comment]
I was able to get lunr 2 to work with Hugo.  The Pixaby auto-complete library was causing problems.  

(1) If I use the bevacqua horsey library or (2) if I don't use any auto-complete at all, then search with tags and search in general works.

**Comment by olivernn** [comment]
It sounds like this issue is resolved? Was it a problem in the auto-complete libraries? If there is still something specific to Lunr you want me to look into please comment and I'll re-open.
