### ISSUE TITLE
Tokenization of Camel Case

### ISSUE THREAD

**Issue by hammadzz** [olivernn/lunr.js#372]
Why is camelcase not tokenized? When I am searching for "foo" the result will show up for "foo-bar" but not for "fooBar"

Do I need to write a custom tokenizer?

**Comment by olivernn** [comment]
If you search for "foo*" you _should_ see results for "fooBar".

Lunr splits strings into tokens based on this [regex](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L69-L76), you can override this to get different behaviour.

In this case though it _might_ be better off writing a [custom pipeline function](https://lunrjs.com/guides/customising.html#pipeline-functions) to split a camel cased word. I think there are examples of how to do this in some other (possibly closed) issues, #301 seems similar.

**Comment by olivernn** [comment]
This looks to have gone stale, resolving.
