### ISSUE TITLE
`position` is not correct when field starts with whitespace

### ISSUE THREAD

**Issue by sulf** [olivernn/lunr.js#386]
In https://github.com/olivernn/lunr.js/blob/f9aeea2c592dc08eec67937bcb5b34903e6c04dc/lib/tokenizer.js#L38 we're trimming the input string and using that for position calculation later in https://github.com/olivernn/lunr.js/blob/f9aeea2c592dc08eec67937bcb5b34903e6c04dc/lib/tokenizer.js#L50.

Here's a quick test case to verify this issue:
```
var lunr = require('lunr');

var idx = lunr(function () {
    this.metadataWhitelist = ['position'];
    this.ref('id');
    this.field('name');
    this.add({ id: 1, name: '     love is in the air!'});
});

var results = idx.search("love");

// `position` should be [5, 4] but is [0, 4]
var position = results[0].matchData.metadata['love'].name.position;
console.log(position);
```

**Comment by olivernn** [comment]
A fix for this has just been released in 2.3.7
