### ISSUE TITLE
how to remove duplicate entries from local json index?

### ISSUE THREAD

**Issue by monikagupta78** [olivernn/lunr.js#396]
I have some collections in Jekyll on which I am performing lunr search. Issue is my collections have some common entries/md files so in search for same keyword, it is showing two same results.

Is there a way i can remove same entries (based on a field say title) from the main index?

or handle to remove duplicate entries from search results. I feel first option be ideal.

Any inputs pls.

**Comment by hoelzro** [comment]
Hi @monikagupta78!

Can you provide some code that demonstrates which version of lunr you're using, and reproduces your issue? That would help us solve your issue more quickly!

**Comment by olivernn** [comment]
This seems to have gone stale, going to close. I'll gladly take a closer look if you can provide a simple reproduction case for us to look at though.
