### ISSUE TITLE
Error in some search queries

### ISSUE THREAD

**Issue by tinganho** [olivernn/lunr.js#40]
I got this error on some certain search queries

TypeError: Cannot read property 'tf' of undefined    at lunr.Index.documentVector (/usr/local/lib/node_modules/grunt-translate/node_modules/lunr/lunr.js:1104:53)    at lunr.Index.search (/usr/local/lib/node_modules/grunt-translate/node_modules/lunr/lunr.js:1076:61)    at Array.map (native)    at lunr.SortedSet.map (/usr/local/lib/node_modules/grunt-translate/node_modules/lunr/lunr.js:574:24)    at lunr.Index.search (/usr/local/lib/node_modules/grunt-translate/node_modules/lunr/lunr.js:1075:6)    at Search.query (/usr/local/lib/node_modules/grunt-translate/src/modules/search.js:93:24)    at module.exports (/usr/local/lib/node_modules/grunt-translate/app/modules/search/searchApi.js:9:21)    at callbacks (/usr/local/lib/node_modules/grunt-translate/node_modules/express/lib/router/index.js:161:37)    at param (/usr/local/lib/node_modules/grunt-translate/node_modules/express/lib/router/index.js:135:11)    at pass (/usr/local/lib/node_modules/grunt-translate/node_modules/express/lib/router/index.js:142:5)

**Comment by olivernn** [comment]
Wow, this is an old issue! I've pushed changes now in [0.6.0](https://github.com/olivernn/lunr.js/releases/tag/v0.6.0) that should solve this issue, let me know if you still have issues with the latest version.
