### ISSUE TITLE
Make Plugins More Accessible 

### ISSUE THREAD

**Issue by indolering** [olivernn/lunr.js#400]
It's hard to find Lunr plugins and I thought of a few things I've found in other projects that could work here:

* Plugin list, either on a wiki page or an [awesome list](https://awesomelists.top/).
* Section dedicated to plugins in the README and on the website.
* Create a convention of `lunr-name` for lunr plugins, akin to Gulp or Grunt.

**Comment by olivernn** [comment]
That sounds like a great idea. There is a [guide](https://lunrjs.com/guides/language_support.html) on using the lunr-languages plugin, but I'd be happy to add a page on the website with a list of plugins.

Was there a specific list of plugins that you eventually found that you can recommend? Or were you looking for a particular plugin to solve a specific issue?

**Comment by indolering** [comment]
>  There is a guide on using the lunr-languages plugin,

Yes, but none of your plugin related development is very discoverable because it's not clearly labeled.

> Was there a specific list of plugins that you eventually found that you can recommend?

Nope.

> There is a guide on using the lunr-languages plugin,

There was a ticket where someone was trying to merge in a feature that would have been better off as a plugin.  AFAICT, nothing ever happened ... a sad failure to capture outside engagement.

**Comment by olivernn** [comment]
I'm going to close this one now as I'm not sure what that it is particularly actionable. I'm more than happy to feature other plugins on the website though. Please comment/re-open this issue if there are any specific plugins that should be featured.

**Comment by indolering** [comment]
Create a plugin page on the wiki.  The wiki was enabled, but without any content so I initialized a home page and an example [list of plugins](https://github.com/olivernn/lunr.js/wiki/Plugins).  Feel free to revert.

**Comment by olivernn** [comment]
@indolering thanks for taking a stab at this, I think ultimately this should sit in the website, but I don't think it hurts to have it here.
