### ISSUE TITLE
PHP Indexer

### ISSUE THREAD

**Issue by acouch** [olivernn/lunr.js#409]
Just a heads up that I created a PHP implementation of the indexer: https://github.com/CivicActions/lunr.php

This could be useful for anyone that wants to use Lunr.js but doesn't have node on the server (ie Drupal, Wordpress etc).

It doesn't have boosts and some of the features. Feel free to close this once you've read it.

**Comment by acouch** [comment]
Closing this as it was created for visibility. Thanks @olivernn for the amazing library. Excited to use it in some high-profile sites and to make it easier for folks using PHP to implement.

**Comment by olivernn** [comment]
@acouch sorry for not responding earlier, this is _awesome_ work, thank you for sharing! I think I'll put together a page in the documentation about this and the [python](https://github.com/yeraydiazdiaz/lunr.py) implementation.
