### ISSUE TITLE
how to retrieve field value based on returned ref id ???

### ISSUE THREAD

**Issue by hoogw** [olivernn/lunr.js#415]
I have read more than 5 closed request asking for this function since 2014.

As of today 2019, 5 years, still think this function is in great need. 

Now it only gives your ref id,  but I want to get the real field value associate with that id.

if I use

                   array.find(function(doc){
      
                   if (ref-id == array.field) {
                       return array
                                                      }

                 });  

   this will loop the whole json array, overhead of cpu and ram is huge. 
   use of array.find() will make lunr.js meaningless.
   The purpose of use lunr.js is quickly find ref id. 
    To retrieve the full field value associate with that ref id, I have to loop whole array again, 
     then why use lunr.js, you could just only use array.find() to get it. 

    On my pc, array.find() for 4k records, cost 0.4 second,
    lunr.js can reduce it by 90%, however, the last step is get full field value, 
    I don't know how to

**Comment by hoogw** [comment]
The work around is:  without change lunr.js.

use object {key: value} or associate array array[key] = value

In this case:

          you could create a new object as 

              newObject = {id: {id:xx, name: YYY}}   then you access the full field value by newObject[id]
    
            the performance is really fast than original array.   array.find(function (id)) {..............}


            Another choice is use associate array,  array[id]= {id:xxx, name: yyy}
            access full field by,   array[id], performance is similar as object() above.

**Comment by olivernn** [comment]
Every time this feature gets requested it is rejected for the same reasons: this is something that is very application specific and, as your own comment shows, can be trivially implemented without any changes to lunr.
