### ISSUE TITLE
Tokenizer trimming causes offset matches if document content begins with whitespace

### ISSUE THREAD

**Issue by rgaiken** [olivernn/lunr.js#417]
If a document starts with a whitespace character, `trim()` in [`tokenizer.js`](/olivernn/lunr.js/blob/master/lib/tokenizer.js#L38) will remove those characters, causing the returned match data to be offset.

See [this fiddle](https://jsfiddle.net/5wq3rf2n/) for a simple example

**Comment by hoelzro** [comment]
Thanks for the report @rgaiken ! I wrote up a fix in #418

**Comment by olivernn** [comment]
I've just pushed 2.3.7 which includes the fix provided by @hoelzro .
