### ISSUE TITLE
npmjs version of 2.3.7 doesn't contain lunr.min.js, but 2.3.6 does.

### ISSUE THREAD

**Issue by karendolan** [olivernn/lunr.js#420]
Hi @olivernn,

Would it be possible to publish  an incrementally newer version of lunr.js to npmjs that contains a lunr.min.js? The lunr.js 2.3.6 version contains a lunr.min.js , but 2.3.7 doesn't.

I use the Paella video player, and it's gulp build expects a lunr.min.js https://github.com/polimediaupv/paella/blob/develop/gulpfile.js#L181

Thank you and best regards,
Karen

**Comment by olivernn** [comment]
I'm surprised that 2.3.6 did include a minified version of lunr, I was under the impression that I had stopped building a minified version as part of the release process a long time ago.

I think instead you should encourage the Paella maintainers to minify/bundle their dependencies separately.

Sorry I couldn't be of more help, but I do not intend to vend a pre-minified version of lunr now or in the future.
