### ISSUE TITLE
Pipeline functions returning null does not discard token

### ISSUE THREAD

**Issue by StephenCleary** [olivernn/lunr.js#422]
The [documentation](https://lunrjs.com/docs/lunr.PipelineFunction.html) states "A pipeline function can indicate that the passed token should be discarded by returning null. This token will not be passed to any downstream pipeline functions and will not be added to the index."

However, [the code](https://github.com/olivernn/lunr.js/blob/532d990ec2ed68ee78eb8d6b87cf61f525457ab0/lunr.js#L676) checks for `undefined` or empty string, and will pass `null` tokens through to the next pipeline function.

**Comment by hoelzro** [comment]
Can confirm via [fiddle](https://jsfiddle.net/xspotknj/)

The [documentation for the module](https://github.com/olivernn/lunr.js/blob/532d990ec2ed68ee78eb8d6b87cf61f525457ab0/lunr.js#L485-L488) itself implies that `undefined` is indeed the right value to return, and there's [a test](https://github.com/olivernn/lunr.js/blob/532d990ec2ed68ee78eb8d6b87cf61f525457ab0/test/pipeline_test.js#L145-L165) that backs this up

**Comment by hoelzro** [comment]
I've submitted a PR to address this: #423

**Comment by olivernn** [comment]
I think the right fix here is to treat a `null` in the same way the code currently treats `undefined` and `""`

@hoelzro thanks for the pull request, but I think we can take this opportunity to make the code match the documentation! I'll put together a change with a fix just now.

**Comment by olivernn** [comment]
I've just pushed 2.3.8 which includes a fix for this issue, thanks for taking the time to report and to @hoelzro for investigating.
