### ISSUE TITLE
How to integrate indexeddb or pouchdb or watermelondb to save index???

### ISSUE THREAD

**Issue by prog20901** [olivernn/lunr.js#425]
How to integrate indexeddb or pouchdb or watermelondb to save index???

I don't want to accept files from user every time...I don't want to create index everytime...However the user will have files locally...It should be indexed offline and search offline..

Please let me know whether we can store the files in above db, store the lunr.js created index in the above and does the search everytime...

Lunr.js is awesome but wanted to know the above..Please help

**Comment by hoelzro** [comment]
@prog20901 One thing you could do is use lunr's JSON serialization/deserialization functionality as described [here](https://lunrjs.com/guides/index_prebuilding.html) to build up the index, and then use whatever storage API (whether that be indexeddb, local storage, etc) to retrieve the stored index on page load.

**Comment by prog20901** [comment]
Thanks a lot...
