### ISSUE TITLE
Issues loading pre-builded indexes on mobile

### ISSUE THREAD

**Issue by bulby97** [olivernn/lunr.js#429]
I have a 16mo index to load on mobile. Unfortunately `JSON.parse` is not asynchronous, nor fast and it blocks the UI + take 3+ secondes to load.

Is there any other way to load the index ? Or any other lib I could use ?

**Comment by olivernn** [comment]
There are definitely asynchronous versions of `JSON.parse`, I haven't used any enough to recommend a particular library though. Anything that parses JSON could be used and the result passed to `lunr.Index.load`.
