### ISSUE TITLE
 OR search on  fields with multi terms

### ISSUE THREAD

**Issue by dionsaba** [olivernn/lunr.js#436]
Hello,

I set up a search engine on a JSON file.
I used lunrjs.

My only problem is the search with "OR" on fields which have multi terms.

for example:    name: Jean Paul SARR   OR     Age: 18

I would like it to return **only** all lines with name = "John Paul SARR" and those with Age 18.

Thank you in advance for your help.

sorry for my bad english.
lunr.version = "2.3.6"

**Comment by olivernn** [comment]
This is covered in the [guides](https://lunrjs.com/guides/searching.html#term-presence)

Specifically in your example:

```
+name:dionsaba +age:18
```
