### ISSUE TITLE
Search is extremely slow

### ISSUE THREAD

**Issue by alexey-milovidov** [olivernn/lunr.js#438]
Sorry for so vague description.

If you open https://clickhouse.yandex/docs/en/ and start typing "aaaaaaaaa" in search form, the browser will lock-up for at least a few seconds. It reproduces both in Chromium and Firefox.

I'm not a JS developer and today just figured out that we are using your technology, but I'm not sure if this issue is a drawback of your library or we just using it incorrectly.

All our frontend developers have disappeared and there is nobody to help us :)

**Comment by olivernn** [comment]
Without more detail its difficult to be sure, but this sounds similar to a couple of issues seen in the past:

* https://github.com/olivernn/lunr.js/issues/270
* https://github.com/olivernn/lunr.js/issues/368

This was a bug and a [fix](https://github.com/olivernn/lunr.js/commit/84c160c240fba34e8671733516e250c28c688bc0) was pushed in version 2.3.3.

Can you confirm that the version of lunr you are running is > 2.3.3?

**Comment by alexey-milovidov** [comment]
Yes, we use old version. Though I cannot confirm that this issue is related to that cases.
Thank you!
