### ISSUE TITLE
Sub-fields support?

### ISSUE THREAD

**Issue by sustained** [olivernn/lunr.js#442]
Fuse.js allows us to do stuff like this:
```js
{
  keys: [
    {
      name: 'title',
      weight: 1.0,
    },
    {
      name: 'body',
      weight: 0.75,
    },
    {
      name: 'user.login',
      weight: 0.3,
    },
    {
      name: 'labels.name',
      weight: 0.3,
    },
  ],
}
```
...which is really nice.

AFAICT from the docs/guide, here I would need to flatten the data, right?

But how would that work with e.g. my labels?

Thank you!

**Comment by olivernn** [comment]
A function can be used to 'extract' a field from a document, this is specified when configuring the index, e.g.

```javascript

var fooFieldExtractor = function (doc) {
  return doc.foo.bar.baz
}

lunr(function () {
  this.field("foo", extractor:
    return doc.field.subField
  }
