### ISSUE TITLE
add is not a function

### ISSUE THREAD

**Issue by paopaol** [olivernn/lunr.js#448]
![1f81608f30ba2b187f8e15663a5e027](https://user-images.githubusercontent.com/6983082/77225012-1b995c00-6ba6-11ea-835f-22a5572b5c41.png)

**Comment by rodrigorm** [comment]
The `add` method is defined on build and should be put inside the `lunr` call:

```
lunr(function () {
  this.add(doc);
});
```

**Comment by olivernn** [comment]
Since version 2 adding documents to an index must be done when defining the index, just like @rodrigorm says.
