### ISSUE TITLE
Any way to apply a overall document weight based on specific document type/category/field?

### ISSUE THREAD

**Issue by Tuckie** [olivernn/lunr.js#451]
I currently have a website with slowly changing content along side a blog.

Is there any way to de-prioritize results from the blog pages as opposed to results found elsewhere on the site?

**Comment by olivernn** [comment]
When [adding documents](https://lunrjs.com/docs/lunr.Builder.html#add) to the index you can apply a boost to the document as a whole.

```javascript
lunr(function () {
  this.add(blogPage, { boost: 0.5 })
  this.add(otherPage, { boost: 1.0 }) // this is the default behaviour
})
```

The boost can be less than one to de-prioritise matches.
