### ISSUE TITLE
Recommended setup for searching personal names

### ISSUE THREAD

**Issue by dimaqq** [olivernn/lunr.js#452]
I'm trying to use `lunr.js` to search a list of users client-side.
The data has personal names, user ids and emails, however names could be in several scripts and languages.
I wonder what kind of setup I should use.

**Comment by fex80** [comment]
Here's my thoughts:

- As your searching names, I would not use stemmers
- Not using stemmers the languages/scripts the names are in do not really matter all that much.
- Probably adding some typo-friendlyness would be nice, as names tend to have different spellings ("john miller" vs "jon miller")
- I would take special care to unify as many technical variations to create the same visual character by applying a some sort of unicode collapsing filter to index and search. It's a real rabbit hole, and I would stop at some point but I would think this is really important. Some Links: [When "Zoë" !== "Zoë"](https://withblue.ink/2019/03/11/why-you-need-to-normalize-unicode-strings.html), [Latin and Cyrillic overlat](https://stackoverflow.com/questions/1741236/why-are-there-duplicate-characters-in-unicode) and [a more general SO question](https://softwareengineering.stackexchange.com/questions/368856/why-does-unicode-have-separate-codepoints-for-characters-with-identical-glyphs) 
- To make search results meaningful I'd probably boost the name fields over the mail ans user-id fields
- As you seem to be based in Japan, special care is needed to properly split names and queries into words, the built-in tokenizer might not be ideal

**Comment by olivernn** [comment]
Everything that @fex80 says seems to be excellent advise, not much more I can add. Let us know if you run into any difficulties.
