### ISSUE TITLE
abysmally slow on search term `+*`

### ISSUE THREAD

**Issue by dimaqq** [olivernn/lunr.js#453]
`index.search("+*")` is really really really slow:

<img width="588" alt="Screenshot 2020-04-16 at 10 44 28" src="https://user-images.githubusercontent.com/662249/79405434-5a68d900-7fcf-11ea-8953-32af7214f9de.png">

I guess I just have to validate the search terms before searching, don't I?

**Comment by olivernn** [comment]
What are you trying to achieve with a query of `+*`? I'd say that kind of query would be the pathological case, certainly with the current implementation of lunr.

_If_ you are trying to get all documents from the index, that is better done _outside_ of lunr. It's not really designed to be a general purpose store of documents.

**Comment by dimaqq** [comment]
I was trying to make it work like this:
* given user input `foo bar%$%$`
* strip bad chars `%$...`, split the input, remove whitespace, convert each word into searchy thingy
* and thus search `+foo* +bar*` in `lunr.js`
* receive "everything that has both words starting with foo and starting with bar"

Obv., I had a small bug, and empty user input was converted into `+*`.

I understand that that would return entire dataset and can have some overhead, but I was surprised at just how slow it was.

So I figure, maybe there's a bug?
(or maybe I just shouldn't do this)

**Comment by olivernn** [comment]
> (or maybe I just shouldn't do this)

Yes. :)

What behaviour would you expect when entering this query? What did Lunr return?

It _might_ be possible to intercept certain queries and return something (what though?) to improve performance, I'm not yet sold on this though.

**Comment by dimaqq** [comment]
At the time I used to think that should return everything.
But it seems that's not entirely accurate, I think that objects that are build of only empty strings won't actually match.
Anyway, feel free to close or whatever.
