### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by djaus** [olivernn/lunr.js#457]
On what basis is the sort order determined?
Are there any options on this in the search function?
Any suggestions for this?

I'm using on my blog site [https://davidjones.spotronics.com.au]( https://davidjones.spotronics.com.au])
Which uses Jekyll-Markdown.

**Comment by olivernn** [comment]
The results are sorted by relevance. The first result returned _should_ be the most relevant to the query that was entered.

There isn't any way to alter this in Lunr.
