### ISSUE TITLE
how to asynchronous? (avoid block)

### ISSUE THREAD

**Issue by hoogw** [olivernn/lunr.js#459]
I have very large static json data (150k count)

When I initially create index, it block the browser UI, not responsive, until indexing completed.

Ideally I am ok with long time it took for indexing, as long as it NOT block UI.

I know if I indexing in web worker, it will not block main thread UI.

Can we make lunr.js as asynchronous? like ajax calls, 
when I indexing,  it runs but not block UI, browser keep responsive on other UI task.

**Comment by olivernn** [comment]
First, you should probably look into [pre-building your indexes](https://lunrjs.com/guides/index_prebuilding.html) if the content is relatively static.

It isn't possible to make Lunr indexing asynchronous, it is compute bound and JavaScript is single threaded. If you must build the index in the browser and you don't want to block the UI thread then, as you mention, the indexing needs to be moved off the main thread using WebWorkers or similar.
