### ISSUE TITLE
Way how to escape asterisks "*" in query

### ISSUE THREAD

**Issue by drobnikj** [olivernn/lunr.js#462]
Hey @olivernn,
thanks for an amazing tool in the first place!

It would be great to have some way how to escape asterisks "*" in the search term.

It is not possible to search in index terms like "foo*bar".
```
const results = idx.search('foo*bar');
```
It will return everything from the index, which starts with foo ends bar.

**Comment by fex80** [comment]
Hey @drobnikj: Not a built-in solution, but maybe an idea to get you to move forward quickly: Have you tried if you can get the desired behaviour with `idx.search('+foo* +*bar')` ?

**Comment by olivernn** [comment]
The [search syntax is documented](https://lunrjs.com/docs/lunr.Index.html#~QueryString), though admittedly this could be easier to discover.

Special characters can be escaped using the backslash, so you're query can be written as `foo\*bar`.
