### ISSUE TITLE
How to match a term within a word?

### ISSUE THREAD

**Issue by WisdomSky** [olivernn/lunr.js#463]
For example, If I search `demon`, I would expect it to match both `demon` and `demonstrated`.

**Comment by WisdomSky** [comment]
I have a dataset containing information of items/monsters in a game. Most of them has terms that are glued together like houseboy. And when I search house, it won't show in the results.

**Comment by fex80** [comment]
Hey, @WisdomSky, sounds like you are looking to use [wildcards](https://lunrjs.com/guides/searching.html#wildcards), i.e. you could make your query `house*` or `demon*` to get the results you need.

**Comment by WisdomSky** [comment]
@fex80 thanks for the suggestion, I've already tried that but unfortunately it isn't working.

**Comment by olivernn** [comment]
As @fex80 mentions wildcards are the way to achieve what you are asking for.

> I've already tried that but unfortunately it isn't working.

Are you able to provide a minimal reproduction showing how the wildcards are not working?

**Comment by olivernn** [comment]
Closing this now, I'm more than happy to re-open and help understand whether there is a bug in Lunr for your use case, but I can only do that if you provide a reproduction of the bug.
