### ISSUE TITLE
lunr taking +4 seconds CPU time

### ISSUE THREAD

**Issue by improvethings** [olivernn/lunr.js#465]
I'm using lunr.js with the [minimal-mistakes jeyll theme](https://github.com/mmistakes/minimal-mistakes/). When I try the URL in Chrome, and then go to Audit/Lighthouse, it consistently shows lunr as taking +4-9 seconds total CPU time. 

![lunrjs](https://user-images.githubusercontent.com/16601027/84290156-3241b600-aaf8-11ea-836b-1ed8b24f62ae.png)

$ ls -l _posts/ | wc -l
366

Any suggestions on how to get this under 1 second?

**Comment by olivernn** [comment]
It is probably better to open this issue on the minimal-mistakes theme project, I'm not familiar with how they use Lunr.

I'm _guessing_ that the search index is being built on the client side on each page load. To improve performance then index can be [built server side](https://lunrjs.com/guides/index_prebuilding.html).
