### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by trusktr** [olivernn/lunr.js#467]
reproduce:

- go to https://olivernn.github.io/moonwalkers/
- Notice there is an "Alan Shepard" section in the page.
- Try searching for "shep"
- notice there are no results.

And similar with other searches.

Screenshot:

![lunr-not-working](https://user-images.githubusercontent.com/297678/85085908-1d1af600-b18e-11ea-903b-fb4a93ce6840.png)

**Comment by niknbr** [comment]
I suppose since it is a matching terms, and there is not word `shep` on the page, it would show any results.

Instead we can use wildcard matching `shep*`, in which case it matches `Shepard`. [ref](https://lunrjs.com/guides/searching.html#wildcards)

**Comment by trusktr** [comment]
Ah, I see! Most website searches that I know of work more like a fuzzy finder, which I believe many people expect. 

A few examples:

- https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene
- https://airbnb.io/lottie
- https://www.assemblyscript.org/introduction.html

Is there an option to enable fuzzy search?

**Comment by niknbr** [comment]
Yes it supports fuzzy search like this `shep~1` where 1 is the edit distance. More details [here](https://lunrjs.com/guides/searching.html#fuzzy-matches)

**Comment by olivernn** [comment]
The demo site is intended only to be able to demo the features of Lunr. The input entered in the search box is passed straight to `lunr.Index#search`. This doesn’t add any implicit wildcards or any other modifiers as already mentioned.

You’re right that in many cases wildcard or fuzzy searching would be a user’s expectation. Using [`lunr.Index#query`](https://lunrjs.com/docs/lunr.Index.html#query) it is possible to have that level of control on how a query is interpreted.
