### ISSUE TITLE
Question about field

### ISSUE THREAD

**Issue by SukkaW** [olivernn/lunr.js#468]
I'm building a search engine for a JAMStack website using `lunr.js` and here is the case:

```js
const res = lunr(function() {
  this.ref('url');
  this.field('title');
  this.field('content');
  this.field('tags');
});
```

As code shows above, I add 3 fields, `title`, `content` and `tags`. However, I want field `tags` only be searched when specified. I mean:

- I want `res.search('foo')` only search through field `title` & `content`
- Only when `res.search('tags:foo bar')` should search in the field `tags`.

How should I build my index to achieve this?

**Comment by faizanu94** [comment]
I think what @SukkaW is saying can be achieved by [fields](https://lunrjs.com/guides/searching.html#fields) feature, however @olivernn can suggest better

**Comment by olivernn** [comment]
> How should I build my index to achieve this?

I think you've already built you search index in the correct way to do this. If, when searching, you only want to search specific fields, you can specify those when calling either `search` or `query`

> I want res.search('foo') only search through field title & content

You will have to specify the fields you want to search unless you want to search all of them. Using your example, and the `search` method this would become:

```javascript
res.search("title:foo content:foo")
```
