### ISSUE TITLE
Complete set union is not complete

### ISSUE THREAD

**Issue by bleroy** [olivernn/lunr.js#469]
A union with the complete set should be complete. Instead, the other set is returned. This hides another bug in search where `clauseMatches` is initialized with the complete set instead of the empty set.

**Comment by olivernn** [comment]
Hey, thanks for the fix, I've merged it now. Before I cut a new release though I'd like to understand this:

> This hides another bug in search where clauseMatches is initialized with the complete set instead of the empty set.

Are you saying that there is a bug now that the the union of a complete set is fixed? Was that included in your change, or is there still work to be done?

**Comment by bleroy** [comment]
My fix is for both. It’s just that the second issue was hidden by the first one but both are fixed now.

**Comment by bleroy** [comment]
Second issue is fixed by starting from an empty set in index.js
