### ISSUE TITLE
Conjuctions like the/as/that etc. are not searched

### ISSUE THREAD

**Issue by ar5had** [olivernn/lunr.js#480]
Hi,

It looks like lunr by default, not search for conjunctions. Is there any way to stop this default behaviour?

Example - search for the/as/that on https://olivernn.github.io/moonwalkers/

Related issue - https://github.com/olivernn/moonwalkers/issues/2

Thanks.

**Comment by olivernn** [comment]
These words _are_ filtered out by the [`lunr.stopWordFilter`](https://lunrjs.com/docs/lunr.html#.stopWordFilter). The goal is to remove additional words that are typically not very much use for determining the relevancy of a search to a document.

This behaviour is the default and it can be disabled by removing the `lunr.stopWordFilter` from both the indexing and searching pipelines:

```javascript
lunr(config => {
  config.pipeline.remove(lunr.stopWordFilter)
  config.searchPipeline.remove(lunr.stopWordFilter)
})
```
