### ISSUE TITLE
lunr.Index.prototype.idf() seems to fail when the term is an all-lowercase property of Object.prototype.

### ISSUE THREAD

**Issue by gitgrimbo** [olivernn/lunr.js#64]
For example, an index with "constructor" or "UNDERUNDERprotoUNDERUNDER" terms in it will cause `idf()` to return the `Object.prototype` property of the same name.

(UNDER is `_`. Used here to avoid GFM stripping the `_`s and turning the property bold)

Because the returned property of `Object.prototype` is not a number, the subsequent calculations return `NaN`.

Pull request with tests to follow.

**Comment by olivernn** [comment]
I believe this is now [fixed](https://github.com/olivernn/lunr.js/commit/1f213775e2705d5393a971dfee9140f63cd636a5)

Please re-open if you continue to see any problems.
