### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by cambridgemike** [olivernn/lunr.js#75]
I just forked the repository (everything is up to date), but I'm getting a test failure. Is this a known test failure or do I have something misconfigured? Was there supposed to be a build step before running the tests?

 ~/code/lunr.js (master) $ make test
Test failed: lunr.tokenizer: calling to string on passed val
    Failed assertion: expected: tue,jan,01,2013, but was: mon,dec,31,2012
    at http://localhost:32423/test/env/qunit.js:472
    at http://localhost:32423/test/tokenizer_test.js:50
    at http://localhost:32423/test/env/qunit.js:136
    at http://localhost:32423/test/env/qunit.js:279
    at process (http://localhost:32423/test/env/qunit.js:1277)
    at http://localhost:32423/test/env/qunit.js:383
Took 58ms to run 297 tests. 296 passed, 1 failed.
make: *** [test] Error 1

**Comment by smikes** [comment]
Is this believed fixed or still open?  Just ran into it today, timezone is America/Edmonton, reproduce it like this:

```
$ TZ=/usr/share/zoneinfo/America/Edmonton  npm test

> lunr@0.5.7 test /Users/smikes/src/github/lunr.js
> make test

Starting test server at http://localhost:32423
Test failed: lunr.tokenizer: calling to string on passed val
    Failed assertion: expected: tue,jan,01,2013, but was: mon,dec,31,2012
    at http://localhost:32423/test/env/qunit.js:472
    at http://localhost:32423/test/tokenizer_test.js:50
    at http://localhost:32423/test/env/qunit.js:136
    at http://localhost:32423/test/env/qunit.js:279
    at process (http://localhost:32423/test/env/qunit.js:1277)
    at http://localhost:32423/test/env/qunit.js:383
Took 54ms to run 301 tests. 300 passed, 1 failed.
```

**Comment by olivernn** [comment]
There has been another [fix](https://github.com/olivernn/lunr.js/commit/32c917a166ddfd2afd825f156854e0cae72834f9) for this issue pushed in the latest release, [0.5.8](https://github.com/olivernn/lunr.js/releases/tag/v0.5.8).

Feel free to re-open if you continue to see similar issues.
