### ISSUE TITLE
different pipelines for indexing and searching

### ISSUE THREAD

**Issue by zs-zs** [olivernn/lunr.js#80]
Hi,

I'm using lunr.js in a project where autocomplete is also a requirement besides of the client-side search. I was able to make the autocomplete work with introducing an additional processing step in the pipeline, just before the stemmer does its work. 
But it's good to see that now there is a possibility to extend the package with the new `use()` api on the index. So I started to extract my solution into a lunr extension, you can check my approach [here](https://github.com/zs-zs/lunr.autocomplete.js).

I'm using a Radix tree to store n-grams of the tokens (right before stemming), later you can use this tree for efficient autocomplete over the stored n-grams.

Unfortunately, there is a problem with this solution - lunr.js calls the indexing pipeline on each search - I can easily understand why you chose this approach: because usually you need the same processing steps (stemming, stop-word filtering, etc.) for the query string which you've used for indexing.

But in this case, I would need an "indexing pipeline" which is different than the "search/query string pipeline". 

Previously I solved this issue in my application in a way that right after indexing, I set a flag to true indicating that indexing has finished, but IMO it's a very hackish solution - if I would like to extract this solution to a lunr extension, we would need a way for configuring different pipelines for search and indexing.

What is your opinion?

**Comment by olivernn** [comment]
This is now supported in version 2 of Lunr which is available on npm now. Please take a look and let me know if you have any feedback, and open an issue if you run into any problems.
