### ISSUE TITLE
Serialize big indexes (get rid of TokenStore?)

### ISSUE THREAD

**Issue by Pym** [olivernn/lunr.js#85]
Hello there,

I'm building a browser based application (without a webserver). I'll have multiple documents to index (in my case, about 700) and the cumulated weight of those documents is about 5 MB.

For now, my application rebuilds the index every time the webpage is displayed, but it takes about 40 seconds to build the full index, which is very long.

I want to store the index in the browser but I can't even serialize it. Here is what I get when I try to `JSON.stringify()` my index:

```
Uncaught RangeError: Maximum call stack size exceeded
```

After a short investigation, the problem seems to come from `JSON.stringify()` which can't handle big object. In fact, after a heap snapshot, it occurs that my TokenStore is about ~ 70 MB..!

![screen shot 2014-04-30 at 15 30 53](https://cloud.githubusercontent.com/assets/89233/2841720/bc008d08-d06b-11e3-9189-145f9e615cc4.png)

I will not even try to store such a big object in a browser, but maybe I'm looking in the wrong way here. Maybe there is a way to store the index without the TokenStore and rebuild it somehow?

Thank you!

**Comment by kig** [comment]
I've been hacking on making the serialized index smaller as I'm trying to do client-side search of the v8 codebase (which is around 120 MB). I've got a small prototype of a packed index up at https://github.com/kig/lunr.js

The unpacked index is 180 MB (20 MB gzipped). The packed index is 20 MB (6.5 MB gzipped). And there's still a good chunk of compression possible. I played with quantizing the termFreqs and that alone dropped the gzipped file size to 1.4 megs.

I have a simple unit test on the serialiser, but haven't tested it on any real datasets.

**Comment by vladimiry** [comment]
@kig what about using client-side archiving, something like this http://pieroxy.net/blog/pages/lz-string/index.html? Also I noticed this `The index size is about half size of lunr.js index file.` on the https://github.com/weixsong/elasticlunr.js page.

**Comment by kig** [comment]
You can play with a live demo at https://tabletree.io - I ended up rolling a simplified search optimized for speed and index wire size. The index is 1MB gzipped and the searches take <20ms, so you get nice live updates as you type.

Client-side archiving might get you 10-20% wire size boost compared to gzip, but you end up spending more time decompressing the data, so I figured I'd just make the source data more gzip-friendly. Building the search index on the client-side is a non-starter as the corpus is a hundred megs in size -- need to build a compressed index off-line and transfer just that to the client.

**Comment by olivernn** [comment]
@kig that is an _awesome_ live demo, reminds me of [this scene in Jurassic Park](https://www.youtube.com/watch?v=dFUlAQZB9Ng)!

**Comment by Prinzhorn** [comment]
I found that the size of the JSON is not the issue but rather the *depth* that causes the call stack size to exceed. In my case I had a few _very_ long words that were indexed. It was caused by blindly using `$('body').text()`, which does not add a white space between the text nodes and can cause very long "words" which do not get tokenized. These result in a very deeply nested object.

I went with something like the following in our indexing script (which uses cheerio to index static html files)

```js
$('body *').map(function() {
    return $(this).text();
}).get().join(' ');
```

**Comment by olivernn** [comment]
Three years later there is a major new version of Lunr, 2.x, which has a much simpler serialised structure. [Upgrading](https://lunrjs.com/guides/upgrading.html) to this latest version should _hopefully_ alleviate any issues with trying to serialise the large, deeply nested, data structure that Lunr 0.x and 1.x have.
