### ISSUE TITLE
Add support for storing/retrieving field values

### ISSUE THREAD

**Issue by pentode** [olivernn/lunr.js#88]
I've made a (successful!) first pass at adding support for storing/retrieving field values.  I added a fieldStore property to lunr.Index and populate that when the stored property of the field is true, e.g., 

``` javascript
var index = lunr(function () {
  this.ref('id');
  this.field('title',{boost:20, store: true});
  this.field('subtitle',{boost:10, store: true});
  this.field('bio',{boost:5});
  this.field('toc',{boost:5});
  this.field('desc',{boost:4});
});
```

and the result from lunr.Index.search(...) is

```
[ { ref: '4371',
    score: 0.02380936053390949,
    fields: 
     { title: '...',
       subtitle: '...' } },
  { ref: '395',
    score: 0.002723523438116153,
    fields: { title: '...' } } ]
```

To keep the serialize/deserialize functionality, I had to tweak the lunr.Store.load method so it isn't directly coupled to lunr.SortedSet, because the value of lunr.Store entries is now an object instead of a SortedSet.  Maybe I shouldn't have used lunr.Store for this new fieldStore property, though?

If this is a feature that you'd like to have added, I'll clean up my work and make sure all tests are passing...

**Comment by hoogw** [comment]
In 2019 I have same need !!!!

the return result only show ref id. 
I actually want the real full json item associate with that ref id!!!

Otherwise, how I am going to use the returned ref id to retrieve the real full json element?

**Comment by raghur** [comment]
@pentode I know it's ages ago - but by any chance can you throw up your modification as a gist or something?

**Comment by Uzay-G** [comment]
This would be pretty useful. Maybe it could be set as an option?
