### ISSUE TITLE
make indexing faster (not an issue)

### ISSUE THREAD

**Issue by palominoz** [olivernn/lunr.js#99]
Hello there. I am trying `lunr` to index ~40.000 documents. It gets 10x slower when cursor is at about 25.000. Any suggestion on how to speed up this process?

**Comment by olivernn** [comment]
Closing. A number of changes have been introduced that should make indexing faster. There is always scope to make it faster still, but I would need some benchmarking/profiling to help identify the specific issues in this case. Please do re-open if you are still having problems though.
